### ISSUE TITLE
About MASLayoutConstraint

### ISSUE THREAD

**Issue by TheSolitary** [SnapKit/Masonry#190]
If want to use mas_updateConstraints or mas_remakeConstraints methods,they must be MASLayoutConstraint class.Why not NSLayoutConstraint?If it do this,it can update the Xib's Constraints.I editor some code .

```
    for (NSLayoutConstraint *existingConstraint in self.installedView.constraints.reverseObjectEnumerator) {
        //if (![existingConstraint isKindOfClass:MASLayoutConstraint.class]) continue;
        if (existingConstraint.firstItem != layoutConstraint.firstItem) continue;
        if (existingConstraint.secondItem != layoutConstraint.secondItem) continue;
        if (existingConstraint.firstAttribute != layoutConstraint.firstAttribute) continue;
        if (existingConstraint.secondAttribute != layoutConstraint.secondAttribute) continue;
        if (existingConstraint.relation != layoutConstraint.relation) continue;
        if (existingConstraint.multiplier != layoutConstraint.multiplier) continue;
        if (existingConstraint.priority != layoutConstraint.priority) continue;

        return (id)existingConstraint;
    }
    return nil;
```

Do you think so ?

(eg:My english is not well ,ignore it please!)

**Comment by robertjpayne** [comment]
@TheSolitary unfortunately we have no way to know where IB installs their constraints so even if we did use NSLayoutConstraint it wouldn't work.

If you look closely at the method we only compare against constraints in the `self.installedView.constraints` which are constraints generated explicitly by Masonry.

My best advice would be to set any constraints you need to update/remake from IB as "placeholder" and create them in `viewDidLoad` with Masonry instead, then you can update/remake them.
