### ISSUE TITLE
How to put it into my own project?

### ISSUE THREAD

**Issue by TantorL** [SnapKit/Masonry#193]
Hi,I cannot put it into my own project?Can you tell me how to do it?Thank you!

**Comment by liuxuan30** [comment]
Check the demo project, it should give you enough details.

**Comment by robertjpayne** [comment]
We strongly recommend Cocoapods integration and there's instructions towards the bottom of the repo home page. Else you can add it as a subproject or directly integrate the source.

**Comment by TantorL** [comment]
Thank you! I have no contact with Cocoapods before, so when i saw several file has nothing to do with Masonry, i donot know which file to add  to my project. Now, i directly put the file named "Masonry" in to my project, it is ok. As for Cocoapods, i will learn next time. Thank you very much!
