### ISSUE TITLE
A problem about relationship between `left` and `width`

### ISSUE THREAD

**Issue by croath** [SnapKit/Masonry#195]
Hey guys I've been using Masonry for a while, but got a little problem recently.

What if I wanna have a View A, the `left` of which is equal to its superview with a quarter of its superview's width offset? How can I make it with Masonry?

Maybe something like:

```objective-c
make.left.equalTo(superview).offset(superview.mas_width.dividedBy(4.0));
```

Thanks for your help.

**Comment by robertjpayne** [comment]
@croath unfortunately Auto Layout doesn't support pinning position attributes to size attributes. Your best  option is to do something like:

```
make.left.equalTo(superview).offset(@([UIScreen mainScreen].bounds.size.width / 4.0));
```

**Comment by croath** [comment]
Thanks @robertjpayne !
