### ISSUE TITLE
Creating constraints without installing

### ISSUE THREAD

**Issue by akaralar** [SnapKit/Masonry#196]
There was a very nice talk from Tyler Fox (creator of purelayout) which explains some nice ways to work with autolayout in general. The talk can be found [here](https://www.youtube.com/watch?v=taWaW2GzfCI), and the relevant part starts at around 30:30 mark and finished around 38. He offers to work with idempotent functions in autolayout, and to achieve minimal duplication of code he added some convenience methods to reinforce that workflow. What I want in masonry is a way to create a set of constants but without installing them to the relevant views, so that we can install them later when we want. The api could be something like `mas_prepareConstraints:` . I don't know if it is possible with the current architecture of the library but it would be very nice to have that in masonry too. I am willing to contribute, but wanted to discuss if this is possible at all.

**Comment by robertjpayne** [comment]
@akaralar this functionality is currently available in SnapKit, while I realise it's Swift only going forward we're going to be limiting and new feature creep into Masonry.

With that said, there is not much harm in using `mas_makeConstraints` and immediately uninstalling the results. Auto Layout works on the run loop and you shouldn't have any side effects of having them installed for a brief second.
