### ISSUE TITLE
Scrollview + label doesn't align right (margin offset doesn't work)

### ISSUE THREAD

**Issue by donpironet** [SnapKit/Masonry#198]
I'm having a scrollview and in that scroll 1 uilabel. Now I want the scrollview fill the whole screen but the label must have offsets so it doesn't stick to the egdes of the screen.

How I do this right now is like this:

    self.view.backgroundColor = [UIColor whiteColor];
    _scrollView = [[UIScrollView alloc] init];
    _scrollView.backgroundColor = [UIColor whiteColor];

    [self.view addSubview:self.scrollView];

    [self.scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.width.and.height.equalTo(self.view);
        make.center.equalTo(self.view);
    }];

    _label = [[UILabel alloc] init];
    _label.numberOfLines = 0;
    _label.lineBreakMode = NSLineBreakByWordWrapping;

    [self.scrollView addSubview:self.label];

    [_label mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.scrollView).offset(15);
        make.width.equalTo(self.scrollView).offset(-15);
    }];

The constraints off my _label seems weird. But I tried so many things and nothing works. I just want that my label has an offset of 15 all sides. How can I fix this?

**Comment by robertjpayne** [comment]
@donpironet scroll views are funky you never ever want to constrain something to the width or height of a scroll view. Rather constrain it to the scroll view's superview or something else inside the scroll view.

```objc
make.width.equalTo(self.view).offset(-30);
make.height.equalTo(self.view).offset(-30);
make.top.left.equalTo(self.scrollView).offset(15.0);
make.bottom.right.equalTo(self.scrollView).offset(-15.0);
```

Hope this helps.
