### ISSUE TITLE
How to set up multiple relationship

### ISSUE THREAD

**Issue by winterzou** [SnapKit/Masonry#199]
Such as I want to make the width of a view is another three times the width of the view,Or let the width of a view is one-third of its superview

**Comment by lluisgerard** [comment]
What you need is `multipliedBy()`
Look at the examples, there are some that are made using this method.

Also, take a look at this issue:
https://github.com/SnapKit/Masonry/issues/131

Hope this can help :)

**Comment by robertjpayne** [comment]
@winterzou what @lluisgerard is correct. Use the `multipliedBy` or `dividedBy` chain methods.

**Comment by winterzou** [comment]
yes. thx u.

**Comment by xilin** [comment]
What if I want to set the width of a view as the sum of the other two view?
