### ISSUE TITLE
issue on ios6

### ISSUE THREAD

**Issue by zhigangfang** [SnapKit/Masonry#200]
ios6 can't support auto layout margin,
![screen shot 2015-05-19 at 9 53 33 am](https://cloud.githubusercontent.com/assets/3981274/7694007/ed6ff9f8-fe0c-11e4-93be-3cfbe83d0651.png)
how to resolve it? please help me.

**Comment by cloudkite** [comment]
@zhigangfang You can use a version before margins was added https://github.com/SnapKit/Masonry/tree/1ff3602d1c54cfd12be49bf44a3c3bc45b02b258
