### ISSUE TITLE
CenterX question

### ISSUE THREAD

**Issue by NunchakusHuang** [SnapKit/Masonry#202]
i add three button in a UIView,the three buttons size is equal.and i want to make the space between three buttons is equal,how can i do it ?
i have write below code:
button1:
[button1 mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.equalTo(self);
            make.centerX.equalTo(self).multipliedBy(0.5);
}];

button2
[button2 mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerX.equalTo(self);
            make.centerY.equalTo(self);
}];

button3:
[button3 mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.equalTo(self);
            make.centerX.equalTo(self.mas_centerX).multipliedBy(1.5);
}];

the button2 position is right ,but button1 and button3 is wrong,can you tell me why?

**Comment by atbj505** [comment]
how about do ti like this:
__weak ViewController *weakSelf = self;
[button1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(ws.view);
        make.centerX.equalTo(ws.view.mas_centerX).multipliedBy(0.5);
        make.width.equalTo(@50);
        make.height.equalTo(@50);
    }];
    
    [button2 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(ws.view.mas_centerX);
        make.centerY.equalTo(ws.view.mas_centerY);
        make.width.equalTo(@50);
        make.height.equalTo(@50);
    }];
    
    [button3 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(ws.view);
        make.centerX.equalTo(ws.view.mas_centerX).multipliedBy(1.5);
        make.width.equalTo(@50);
        make.height.equalTo(@50);
    }];

**Comment by atbj505** [comment]
- how about write like this:
```objc
__weak ViewController *weakSelf = self;
NSInteger width = 50;
NSInteger height = 50;

[button1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(ws.view);
        make.centerX.equalTo(ws.view.mas_centerX).multipliedBy(0.5);
        make.width.equalTo(@(width));
        make.height.equalTo(@(height));
}];

[button2 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(ws.view.mas_centerX);
        make.centerY.equalTo(ws.view.mas_centerY);
        make.width.equalTo(@(width));
        make.height.equalTo(@(height));
}];

[button3 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(ws.view);
        make.centerX.equalTo(ws.view.mas_centerX).multipliedBy(1.5);
        make.width.equalTo(@(width));
        make.height.equalTo(@(height));
}];
```
