### ISSUE TITLE
use  Masonry Error

### ISSUE THREAD

**Issue by 1036938520** [SnapKit/Masonry#203]
I add the following code on ViewController：
UIView *topView = UIView.new;
    topView.backgroundColor = UIColor.greenColor;
    topView.layer.borderColor = UIColor.blackColor.CGColor;
    topView.layer.borderWidth = 2;
    [self.view addSubview:topView];
    
    UIView *bottomView = UIView.new;
    bottomView.backgroundColor = UIColor.redColor;
    bottomView.layer.borderColor = UIColor.blackColor.CGColor;
    bottomView.layer.borderWidth = 2;
    [self.view addSubview:bottomView];
    
    
    
    
    [topView mas_makeConstraints:^(MASConstraintMaker *make) {
        UIView *topLayoutGuide = (id)self.topLayoutGuide;
        make.top.equalTo(topLayoutGuide.mas_bottom);
        make.left.equalTo(self.view);
        make.right.equalTo(self.view);
        make.height.equalTo(@40);
    }];
    
    [bottomView mas_makeConstraints:^(MASConstraintMaker *make) {
        UIView *bottomLayoutGuide = (id)self.bottomLayoutGuide;
        make.bottom.equalTo(bottomLayoutGuide.mas_top);
        make.left.equalTo(self.view);
        make.right.equalTo(self.view);
        make.height.equalTo(@40);
    }];

In the following error, under what reason be excuse me?

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_makeConstraints:]: unrecognized selector sent to instance 0x7fe92ad4a160'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105c00c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103f99bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000105c080ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000105b5e13c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000105b5dcd8 _CF_forwarding_prep_0 + 120
	5   MasonryTest                         0x0000000103a680cd -[ViewController viewDidLoad] + 1133
	6   UIKit                               0x000000010430c210 -[UIViewController loadViewIfRequired] + 738
	7   UIKit                               0x000000010430c40e -[UIViewController view] + 27
	8   UIKit                               0x00000001042272c9 -[UIWindow addRootViewControllerViewIfPossible] + 58
	9   UIKit                               0x000000010422768f -[UIWindow _setHidden:forced:] + 247
	10  UIKit                               0x0000000104233e21 -[UIWindow makeKeyAndVisible] + 42
	11  UIKit                               0x00000001041d7457 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2732
	12  UIKit                               0x00000001041da1de -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	13  UIKit                               0x00000001041d90d5 -[UIApplication workspaceDidEndTransaction:] + 179
	14  FrontBoardServices                  0x0000000106ecd5e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	15  CoreFoundation                      0x0000000105b3441c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	16  CoreFoundation                      0x0000000105b2a165 __CFRunLoopDoBlocks + 341
	17  CoreFoundation                      0x0000000105b29f25 __CFRunLoopRun + 2389
	18  CoreFoundation                      0x0000000105b29366 CFRunLoopRunSpecific + 470
	19  UIKit                               0x00000001041d8b42 -[UIApplication _run] + 413
	20  UIKit                               0x00000001041db900 UIApplicationMain + 1282
	21  MasonryTest                         0x0000000103a68d1f main + 111
	22  libdyld.dylib                       0x00000001068b8145 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by robertjpayne** [comment]
@1036938520 sounds like Masonry isn't being included in the project properly. Are you using Cocoapods or Carthage or how are you adding Masonry to your applications target?

**Comment by 1036938520** [comment]
Thank you, by asking a friend has been resolved

**Comment by ivanyang1984** [comment]
what is the solution? i found that as well , pls  kindly help it.
