### ISSUE TITLE
Using Masonry in tableView's tableFooterView will show some issues

### ISSUE THREAD

**Issue by huangxinyu1213** [SnapKit/Masonry#204]
i created a tableView in ViewController,and created a tableFooterView for this tableView
like this:
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain];
    self.tableView.backgroundColor = [UIColor cyanColor];
    self.tableView.tableFooterView = [self getFooterView];
    self.tableView.delegate = self;
    self.tableView.dataSource = self;
    [self.view addSubview:self.tableView];
    __weak __typeof(&*self) weakSelf= self;
    [self.tableView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.mas_equalTo(weakSelf.view).with.insets(UIEdgeInsetsMake(0, 0, 0, 0));
    }];
}

And next is my creation for this footView:

- (UIView *)getFooterView
{
    __weak __typeof(&*self) weakSelf= self;
    
    self.footerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 200)];
    self.footerView.backgroundColor = [UIColor yellowColor];
    
    self.redView = [UIView new];
    self.redView.backgroundColor = [UIColor redColor];
    [self.footerView addSubview:self.redView];
    
    [self.redView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.mas_equalTo(weakSelf.footerView).with.insets(UIEdgeInsetsMake(30, 30, 30, 30));
    }];
    
    return self.footerView;
}

i think everything is ok,but,Xcode log some issues : 

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    MASLayoutConstraint:0x7fdd33e53560 UIView:0x7fdd33e51700.left == UIView:0x7fdd33e51550.left + 30,
    MASLayoutConstraint:0x7fdd33e53b10 UIView:0x7fdd33e51700.right == UIView:0x7fdd33e51550.right - 30,
    NSLayoutConstraint:0x7fdd33e6abb0 UIView:0x7fdd33e51550.width == 0
)

Will attempt to recover by breaking constraint 
MASLayoutConstraint:0x7fdd33e53b10 UIView:0x7fdd33e51700.right == UIView:0x7fdd33e51550.right - 30

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by robertjpayne** [comment]
@huangxinyu1213 unfortunately support for Auto Layout in table header/footers is really poor and there's not much we can do about it.

Even using the raw NSLayoutConstraint methods causes a heap of issues. Your best bet is to wrap your view inside another UIView with a fixed size.

```objc
UIView *headerContainerView = [[UIView alloc] initWithFrame:CGRectMake(0,0,UIScreen.mainScreen.bounds.size.width, 300)];
tableView.tableHeaderView = headerContainerView;
```

**Comment by wanghb1027** [comment]
@robertjpayne I found that mas_distributeViewsAlongAxis also have some issues in tableHeaderView.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x1c08a64e0 UILabel:0x130424020.left == UIView:0x13042f440.left + 15>",
    "<MASLayoutConstraint:0x1c02b1a60 UILabel:0x12bd2a830.width == UILabel:0x130424020.width>",
    "<MASLayoutConstraint:0x1c02b5cc0 UILabel:0x12bd2a830.left == UILabel:0x130424020.right>",
    "<MASLayoutConstraint:0x1c0ca3cc0 UILabel:0x12bdc0200.width == UILabel:0x12bd2a830.width>",
    "<MASLayoutConstraint:0x1c08a7980 UILabel:0x12bdc0200.left == UILabel:0x12bd2a830.right>",
    "<MASLayoutConstraint:0x1c02b28a0 UILabel:0x12bdc0200.right == UIView:0x13042f440.right - 15>",
    "<MASLayoutConstraint:0x1c02b2840 UIView:0x13042f440.left == RecordHeadViewNew:0x12beb1410.left>",
    "<MASLayoutConstraint:0x1c02b59c0 UIView:0x13042f440.right == RecordHeadViewNew:0x12beb1410.right>",
    "<NSLayoutConstraint:0x1c409e690 RecordHeadViewNew:0x12beb1410.width == 0>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x1c08a7980 UILabel:0x12bdc0200.left == UILabel:0x12bd2a830.right>

I think is be caused by the superview's width, but when I set the width, the tableHeaderView will been shown confused.
So how to fix the issues?  Thank you for your reply!
