### ISSUE TITLE
how to access each constraint after mas_make called

### ISSUE THREAD

**Issue by caofei10119** [SnapKit/Masonry#205]
I made constraints using mas_make function like

make.left.top.right.bottom.equalTo(self.view);

but not sure how to access topConstraint.
Please help, thanks

**Comment by cloudkite** [comment]
If you want to hold onto a reference to one particular constraint you will need to seperate your constraints

```
self.topConstraint = make.top.equalTo(self.view);
make.left.right.bottom.equalTo(self.view);
```

please have a look at https://github.com/SnapKit/Masonry#1-references

**Comment by caofei10119** [comment]
thanks

**Comment by caofei10119** [comment]
I need to get NSLayoutConstraint Object
