### ISSUE TITLE
Layout giudes on iOS 9

### ISSUE THREAD

**Issue by dlahyani** [SnapKit/Masonry#207]
On iOS 7 (if I am not mistaken) Apple introduced two new properties to <code>UIViewController</code>: <code>topLayoutGuide</code> and <code>bottomLayoutGuide</code>. These properties can be passed as is to auto layout as constraint items. In iOS 7 and 8 these are actually <code>UIView</code> objects that implements the <code>UILayoutSupport</code> protocol and as <code>UIView</code>s they fit well as layout items for Masonry. 
However on iOS 9 these layout guides are of kind <code>UILayoutGuide</code> which is not a subclass of <code>UIView</code>, this causes <code>[MASViewConstraint setSecondViewAttribute:]</code> raise an assertion exception when the second attribute is a layout guide.

**Comment by cloudkite** [comment]
@dlahyani Yes happy to accept PRs which have the same API as recently added SnapKit layout guide support see https://github.com/SnapKit/SnapKit/commit/6252444966517bd22c9bb673c8a41d8d1c7306ea

**Comment by dlahyani** [comment]
:+1: thanks.
