### ISSUE TITLE
Request for greater flexibility in MASLayoutConstraint default priority

### ISSUE THREAD

**Issue by sibljon** [SnapKit/Masonry#208]
In 30:05 of [_Mysteries of Auto Layout, Part 1_](https://developer.apple.com/videos/wwdc/2015/?id=218) from WWDC 2015, the presenter mentions that by default, constraint priorities aren't set as `UILayoutPriorityRequired`, and that "you should not set them as required."

In practice, my experience has been that constraints with priority required often cause unsatisfiable layout exceptions from the layout engine (for example: most typically, when the width or height of a superview is initially zero, but its subviews have required constraints that can't be satisfied).

Now, given that Masonry is in maintenance mode, and that changing the default priority of MASConstraint would be a huge breaking change, would you be willing to accept a pull request that allowed users of Masonry to set a global default priority on constraints?

I would likely make the same request of SnapKit, but in the case of SnapKit, it might be worth considering changing the global default to something other than required. Though I haven't yet migrated to SnapKit and Swift, so my knowledge here is limited of how it's currently configured.

**Comment by cloudkite** [comment]
@sibljon What do they suggest setting the priority to instead of required?

Seems to contradict what the docs say
https://developer.apple.com/library/ios/documentation/AppKit/Reference/NSLayoutConstraint_Class/
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/AutoLayoutConcepts/AutoLayoutConcepts.html

**Comment by sibljon** [comment]
@cloudkite you're right, from _Auto Layout Concepts_ you linked:

> Priority level. Constraints have a priority level. Constraints with higher priority levels are satisfied before constraints with lower priority levels. The default priority level is required (NSLayoutPriorityRequired), which means that the constraint must be satisfied exactly. The layout system gets as close as it can to satisfying an optional constraint, even if it cannot completely achieve it.

**Comment by sibljon** [comment]
After asking Paul Marcos, the Apple developer evangelist, it turns out that the presenter of the WWDC presentation was talking about content hugging/resistance constraints.

So no change needed in Masonry.

**Comment by cloudkite** [comment]
@sibljon thanks for following up! :+1:
