### ISSUE TITLE
'Auto Layout still required after executing -layoutSubviews. JMSCaptchaTextField's implementation of -layoutSubviews needs to call super.'

### ISSUE THREAD

**Issue by loveNoodles** [SnapKit/Masonry#209]
It's ok while running on iOS8 , but error occurs like below : 
'Auto Layout still required after executing -layoutSubviews. JMSCaptchaTextField's implementation of -layoutSubviews needs to call super.' 
help !

**Comment by loveNoodles** [comment]
error occured while running on iOS7.1

**Comment by robertjpayne** [comment]
@loveNoodles hmm, sounds like this is an issue with `JMSCaptchaTextField` and not Masonry? There's nothing we can do to get that class to call super unfortunately.
