### ISSUE TITLE
How to set width as the sum of the other two views?

### ISSUE THREAD

**Issue by xilin** [SnapKit/Masonry#210]
As the title said, how can I set the width of a view as the sum/diff of the other two view?

**Comment by wizzardchao** [comment]
I think there is no native way to such things in Masonry(even in AutoLayout).
But you can try to make parent.left = view1.left, view1.right=view2.left, view2.right=parent.right.
The 3 constraints you use above are the ones Visual Format Language added when you use AutoLayout.

**Comment by xilin** [comment]
Thanks for the suggestion. I'll try.

**Comment by robertjpayne** [comment]
@xilin yea there is no support for summing two views to a constant unfortunately. This is a Auto Layout issue not a Masonry issue.
