### ISSUE TITLE
Using insets (padding) with lessThanOrEqualTo

### ISSUE THREAD

**Issue by eytanbiala** [SnapKit/Masonry#211]
Hi,

I would like to make a view fit to the width and height of the screen and to give it some padding on the edges. On iPad though, I don't want the view to be the full width of the screen, i.e. it should fit to its contents, but at most it should fit to the screen.

    make.height.and.width.lessThanOrEqualTo(self.view).insets(UIEdgeInsetsMake(22, 22, 22, 22));

I've also tried setting the width and height separately:

    make.width.lessThanOrEqualTo(self.view).with.insets(UIEdgeInsetsMake(0, 22, 0, 22));
    make.height.lessThanOrEqualTo(self.view).with.insets(UIEdgeInsetsMake(22, 0, 22, 0));

But in either case the insets are not applied. What is the correct way to do this?

**Comment by robertjpayne** [comment]
@eytanbiala insets are applied only to left/top/right/bottom as you also need to inset origin not just the dimension of the view.

You can instead do `make.edges.lessThanOrEqualTo(self.view).with.insets(...)`.

**Comment by eytanbiala** [comment]
@robertjpayne Makes sense, thanks!

**Comment by skantus** [comment]
http://snapkit.io/docs/

`make.edges.equalTo(superview).inset(UIEdgeInsets(top: 5, left: 10, bottom: 15, right: 20))`
