### ISSUE TITLE
[_UILayoutSpacer mas_top]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by atcuan** [SnapKit/Masonry#213]
In Xcode 7 beta 2 , iOS 9 SDK will crash if use bottomLayoutGuide like this:

```
UIView *bottomGuide = (UIView *)self.bottomLayoutGuide;
make.bottom.equalTo(bottomGuide.mas_top).offset(50);
```

**Comment by robertjpayne** [comment]
@atcuan any reason not to do `id bottomGuide = (id)self.bottomLayoutGuide.top` instead?

**Comment by atcuan** [comment]
This issue has completed fixd by PR #214,  may be you could merge it.
