### ISSUE TITLE
How do i get a LayoutConstraint 's constant use Masonry, or how do i compare two MASConstraint 's size

### ISSUE THREAD

**Issue by renlongyu** [SnapKit/Masonry#215]
How do i get a LayoutConstraint 's constant use Masonry, or how do i compare two MASConstraint 's size?

**Comment by robertjpayne** [comment]
@renlongyu there's not really any built in support for this. A Masonry constraint can result in multiple NSLayoutConstraint's and they're not easily comparable due to the way they install and sorts.
