### ISSUE TITLE
Aspect Ratio constraint

### ISSUE THREAD

**Issue by halpz** [SnapKit/Masonry#216]
how do I set a constraint on a view's Aspect Ratio?

**Comment by stefanfisk** [comment]
There is an example in the project which shows how to setup aspect constraints.

**Comment by BeauNouvelle** [comment]
This issues comes up in search results in Google, showing an example here would be nice instead of just referring to source code — which can change.

**Comment by gorbat-o** [comment]
Hey, here an example :)
`make.height.equalTo(self.mas_height).multipliedBy(0.4);`
