### ISSUE TITLE
文件缺少

### ISSUE THREAD

**Issue by syyjay** [SnapKit/Masonry#217]
libPods-Masonry iOS Examples.a  这个文件 没有  编译不过

**Comment by xingheng** [comment]
Please, paste the error message you encountered out and convert your Chinese into English. The author of this project mostly can't read it. In this project, at least.

**Comment by robertjpayne** [comment]
Re-open as a new issue with translation if possible. Thanks!

**Comment by gleeeli** [comment]
I was also this issue.    "libPods-Masonry iOS Examples.a"this file in xcode is red
