### ISSUE TITLE
Big bug:constraint issue use in UITableViewController static cell

### ISSUE THREAD

**Issue by MountainHill** [SnapKit/Masonry#218]
1,I'm sure this is bug.Not my wrong use.

2,I'm very sorry,I can not descripe because my poor english(I'm chinese),but I uploaded my sample on disk.
Download link:http://7xk61f.dl1.z0.glb.clouddn.com/Test.zip
You can download and see the problem.The sample is very easy,everyone can read it.

3,My aim is 
1,how this issue happen?
2,how to debug this issue?(like chinese saying "授人以鱼，不如授人以渔")

Thank you very much.

**Comment by wizzardchao** [comment]
Hi, I have checked your code and found the dequeued cell is initialized with frame of CGRectZero. Your constraint-view1.left  = 40 and vieiw1.right = 0 will make view1 with a negative width. So iOS break your right constraint to make it legal.
You can try to call setNeedsLayout & layoutIfNeeded at the last of your cellForIndex and see the log in cosole.

A workaround may be set your cell with a width larger than 40 to make it work.
For example:

    UITableViewCell *cell = [super tableView:tableView cellForRowAtIndexPath:indexPath];
    cell.frame = CGRectMake(0,0,100,100);

**Comment by MountainHill** [comment]
@wizzardchao I try to call setNeedsLayout & layoutIfNeeded,as you say the constraint log in console,but I don not know "iOS break your right constraint to make it legal",do you mean iOS delete right constraint or iOS make  right constraint to -40? Did apple doc say the rule when constraint conflict?

Thank you for your advice.

**Comment by MountainHill** [comment]
@wizzardchao Next is the constraint info:
```
2015-07-06 18:36:58.476 Test[1607:246672] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170097b60 UIView:0x126d11ca0.leading == UIView:0x126d01aa0.leading>",
    "<NSLayoutConstraint:0x170098380 UIView:0x126d01aa0.trailing == UIView:0x126d11ca0.trailing + 20>",
    "<NSLayoutConstraint:0x1700986f0 UIView:0x126d0d490.width == 0>",
    "<NSLayoutConstraint:0x170099190 UIView:0x126d0d490.trailing == UIView:0x126d01aa0.trailing>",
    "<NSLayoutConstraint:0x170099550 UIView:0x126d01aa0.leading == UIView:0x126d0d490.leading + 20>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170098380 UIView:0x126d01aa0.trailing == UIView:0x126d11ca0.trailing + 20>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-07-06 18:36:58.478 Test[1607:246672] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1700986f0 UIView:0x126d0d490.width == 0>",
    "<NSLayoutConstraint:0x170099190 UIView:0x126d0d490.trailing == UIView:0x126d01aa0.trailing>",
    "<NSLayoutConstraint:0x170099550 UIView:0x126d01aa0.leading == UIView:0x126d0d490.leading + 20>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170099190 UIView:0x126d0d490.trailing == UIView:0x126d01aa0.trailing>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-07-06 18:36:58.480 Test[1607:246672] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0x1700b5900 UIView:0x126d0f270.left == UITableViewCell:0x126d07fa0.left>",
    "<MASLayoutConstraint:0x1700b5960 UIView:0x126d0f270.right == UITableViewCell:0x126d07fa0.right>",
    "<MASLayoutConstraint:0x1700b5d20 UIView:0x126d17930.left == UIView:0x126d0f270.left>",
    "<MASLayoutConstraint:0x1700b5ea0 UIView:0x126d17930.right == UIView:0x126d0f270.right - 20>",
    "<NSLayoutConstraint:0x17009b990 UITableViewCell:0x126d07fa0.width == 0>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x1700b5ea0 UIView:0x126d17930.right == UIView:0x126d0f270.right - 20>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

The info is nonsense,Can you explain to me?

**Comment by MountainHill** [comment]
@wizzardchao ,I found this quote in apple doc
"To allow layout to proceed, the system selects a constraint from among the mutually unsatisfiable set and lowers its priority from “required” to an internal value that is not required, but that is higher priority than anything you can externally specify. The effect is that as things change going forward, this incorrectly broken constraint is the first that the system attempts to satisfy. (Note that every constraint in the set is required to begin with, because otherwise it wouldn’t be causing a problem.)"

**Comment by MountainHill** [comment]
@wizzardchao Thank you very much.

**Comment by MountainHill** [comment]
@wizzardchao I debug in xcode,and found a very intristing thing,as in Xcode,it is as follows:
<img width="700" alt="xcode" src="https://cloud.githubusercontent.com/assets/7063621/8537093/7e9ff5d6-248c-11e5-919e-2a8403b2ffb1.png">
but in device,it is as follows,
![iphone](https://cloud.githubusercontent.com/assets/7063621/8537096/8bf53052-248c-11e5-9203-e516789cebcb.png)
I donut know why,do you know?

**Comment by jkyin** [comment]
It's full width in IB, you can see view bounds. But the problem is that why cell.bounds.original.x is -40.

**Comment by MountainHill** [comment]
@jkyin the cell's super view is the table,you can download the source code:
http://7xk61f.dl1.z0.glb.clouddn.com/Test.zip,
So it is very strange.

**Comment by jkyin** [comment]
I changed these code to below:

```
    UIView *view1 = [UIView new];
    view1.backgroundColor = [UIColor redColor];
    [cell addSubview:view1];
    
    [view1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(@(20));
        make.left.equalTo(@(0));
        make.right.equalTo(@(0));
        make.height.equalTo(@(120));
    }];
```

And the red view works well, so I don't know what is your issue.

I think maybe you should read more document about UITableView and Auto Layout.

**Comment by MountainHill** [comment]
@jkyin  thx.
