### ISSUE TITLE
Null Dereference

### ISSUE THREAD

**Issue by spacecoder** [SnapKit/Masonry#221]
Our security team has highlighted a potential security issue in:

MASViewConstraint.m:(Line 357)

Impact:
Most null pointer issues result in general software reliability problems, but if an attacker can intentionally trigger a null pointer dereference, the attacker might be able to use the resulting exception to bypass security logic or to cause the application to reveal debugging information that will be valuable in planning subsequent attacks.

Recommendation:
Implement careful checks before dereferencing objects that might be null. When possible, abstract null checks into wrappers around code that manipulates resources to ensure that they are applied in all cases and to minimize the places where mistakes can occur.

**Comment by robertjpayne** [comment]
@spacecoder can you elaborate? What version of Masonry? Sorry I looked at the current code file and don't see a dereference?

**Comment by spacecoder** [comment]
Our security team uses HP Fortify for scanning objective c code. I'm not sure it's correctly finding drefs as this looks like a fairly common pattern for a locally scoped object:

 MASLayoutConstraint *existingConstraint = nil; <----  Null Dereference ?!

    if (self.updateExisting) {
        existingConstraint = [self layoutConstraintSimilarTo:layoutConstraint];
    }
    if (existingConstraint) {
        // just update the constant
        existingConstraint.constant = layoutConstraint.constant;
        self.layoutConstraint = existingConstraint;
    } else {
        [self.installedView addConstraint:layoutConstraint];
        self.layoutConstraint = layoutConstraint;
        [firstLayoutItem.mas_installedConstraints addObject:self];
    }

**Comment by robertjpayne** [comment]
@spacecoder AFAIK initializing a variable to `nil` zero's it's memory thus preventing a dref. Regardless the local variable isn't ever dref'd anyways?

**Comment by robertjpayne** [comment]
Re-open if you reckon this is still a security issue.

**Comment by spacecoder** [comment]
Thanks for looking. I think we're all good and this is a false positive from Fortify.
