### ISSUE TITLE
Why should I set height and width both in button.frame and mas_makeConstraints

### ISSUE THREAD

**Issue by SeanChense** [SnapKit/Masonry#222]
If I just set height and width(height = width) in mas_makeConstraints with `make.height.equalTo(@16);
            make.width.equalTo(@16);`, it doesn't work. And button.imageView doesn't fill up the button, though setting `setImageEdgeInsets:UIEdgeInsetsMake(0, 0, 0, 0)` which doesn't work.

Only if I set height and width both in button.frame and mas_makeConstraints, will it work.

**Comment by michellezi** [comment]
Actually,you needn't.
You need to add top or centerY or bottom\left or centerX or right constraint.

**Comment by SeanChense** [comment]
@michellezi thank you and I think you are right.
