### ISSUE TITLE
mas_remakeConstraints

### ISSUE THREAD

**Issue by captain-black** [SnapKit/Masonry#227]
```console
po [self.separateLine constraints]
<__NSArrayM 0x170442df0>(
<NSLayoutConstraint:0x170893a60 UIView:0x15ab95f00.height == 1>,
<MASLayoutConstraint:0x1748bd340 UIView:0x15ab95f00.height == 0.5>
)
```
calling mas_remakeConstraints reset height constraint, but it just add a new constraint, the old constraint still there.

**Comment by robertjpayne** [comment]
@captain-black looks like you're getting a constraint added from something else. Masonry's constraints will always have the `MAS` prefix in the debug output. Any chance you could paste more of your code?

**Comment by captain-black** [comment]
@robertjpayne yes,the first constraint was added in storyboard. Is that mean Masonry will not change any other constraint except itself?

**Comment by jonz-tech** [comment]
i got the same problem when i add a constraint in storyboard. when i load an new image from internet,i wanna reset the image size,so i use the mas_remakecontraint or mas_updatecontraint to reset it. but the console log the same error like : property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x163cb710 UIImageView:0x163c2d60.height == 128>",
    "<MASLayoutConstraint:0x164591e0 UIImageView:0x163c2d60.height == 300>"
)


so how to fix this problems? tks guy!

**Comment by robertjpayne** [comment]
@captain-black @jonz-tech Masonry will never touch any constraints added by other libraries or storyboards with the exception that it turns off the 'translates autoresizing masks to constraints' flag.

If you want to play nice with storyboards I suggest you mark your storyboards constraints as 'placeholder' and they wont be installed at runtime thus allowing your code and Masonry to take over.
