### ISSUE TITLE
hello  How to get NSLayoutConstraint when use masonry .?

### ISSUE THREAD

**Issue by wy19901227** [SnapKit/Masonry#229]

**Comment by wy19901227** [comment]
I only can get the MASconstraint, but I really want to get the NSLayoutConstraint when I use masonry.
I know masonry is base on apple.

**Comment by robertjpayne** [comment]
@wy19901227 unfortunately it's not that simple. Masonry assumes ownership of the NSLayoutConstraints and uninstalls/re-creates/re-installs these at various times depending on the APIs you use.

If you need a NSLayoutConstraint for integration with another library I recommend you use the regular Apple API's just for that single constraint and then Masonry for everything else.

Masonry also won't ever touch non Masonry constraints so you don't have to worry about a `mas_remakeConstraints` mucking up one you've created and added with Apple's APIs directly.
