### ISSUE TITLE
Different behaviours in iOS 7 vs iOS 8

### ISSUE THREAD

**Issue by penacristian** [SnapKit/Masonry#233]
I have constraints related to a UIImageView that gets animated and changes its size. In iOS 7, edge constraints related to the animated view update while it's changing its size. In iOS 8 it doesn't. How can I get both different behaviours in both iOS versions?

**Comment by robertjpayne** [comment]
@penacristian it's really hard to say, sounds like it may just be a difference between the layout engine in iOS 7 and 8.

You may find it better to work with a top.left.width.height rather than edges constraint though.

**Comment by robertjpayne** [comment]
@penacristian closing this until you are able to provide further feedback.
