### ISSUE TITLE
user Masonry Error  in MRC

### ISSUE THREAD

**Issue by libiao88** [SnapKit/Masonry#234]
my project is mrc and i dont use cocoapods  i just put it in the project  i build a new targets for Masonry 
and run the project   and crash  the following error is :  
[UITableView mas_makeConstraints:]: unrecognized selector sent to instance 0x14a78400

how to put it in mrc project???

**Comment by robertjpayne** [comment]
@libiao88 any reason you can't use Cocoapods to integrate it?

**Comment by libiao88** [comment]
my company wasn't allow me to use  Cocoapods

**Comment by wizzardchao** [comment]
@libiao88 I think you can just add the -fobjc-arc compiler option to all Masonry's files, and it will work then.

**Comment by robertjpayne** [comment]
@libiao88 yea I think you'll need to flag all the files as ARC compatible with the flag @wizzardchao has mentioned. Sorry I can't assist further it seems to be pretty specific to your project setup.
