### ISSUE TITLE
Unable to satisfy the following requirements:

### ISSUE THREAD

**Issue by AliOmari** [SnapKit/Masonry#238]
when trying to install pod i got
Analyzing dependencies
Fetching podspec for `Masonry` from `./`
[!] Unable to satisfy the following requirements:

- `Masonry (from `./`)` required by `Podfile`
- `Masonry (from `./`)` required by `Podfile`
- `Masonry (= 0.6.1)` required by `Podfile.lock`

**Comment by robertjpayne** [comment]
What's your podfile entry look like? Why is it from `./` and what version of Xcode look like?

Looks like you're attempting to reference local pod?

**Comment by AliOmari** [comment]
yea i'm trying to install pod file which i found into Masonry path.
i just entered the path and make pod install
this is my pod file code

workspace 'Masonry'

platform :ios, '6.0'

xcodeproj 'Examples/Masonry iOS Examples'
target 'Masonry iOS Examples', :exclusive => true do
  pod 'Masonry', :path => './'
end

target 'Masonry iOS Tests', :exclusive => true do
  xcodeproj 'Tests/Masonry Tests'
  pod 'Expecta'
end

target 'MasonryTestsLoader', :exclusive => true do
  xcodeproj 'Tests/Masonry Tests'
  pod 'Masonry', :path => './'
end

# add settings needed to generate test coverage data
post_install do |installer|

  COV_TARGET_NAME = "Pods-MasonryTestsLoader-Masonry"
  EXPORT_ENV_PHASE_NAME = "Export Environment Vars"
  EXPORT_ENV_PHASE_SCRIPT = "export | egrep '( BUILT_PRODUCTS_DIR)|(CURRENT_ARCH)|(OBJECT_FILE_DIR_normal)|(SRCROOT)|(OBJROOT)' > $SRCROOT/../script/env.sh"
  
  # find target
  classy_pods_target = installer.project.targets.find{ |target| target.name == COV_TARGET_NAME }
  unless classy_pods_target
   raise ::Pod::Informative, "Failed to find '" << COV_TARGET_NAME << "' target"
  end
       
  # add build settings
  classy_pods_target.build_configurations.each do |config|
    config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'YES'
    config.build_settings['GCC_INSTRUMENT_PROGRAM_FLOW_ARCS'] = 'YES'
  end

  # add build phase
  phase = classy_pods_target.shell_script_build_phases.select{ |bp| bp.name == EXPORT_ENV_PHASE_NAME }.first ||
    classy_pods_target.new_shell_script_build_phase(EXPORT_ENV_PHASE_NAME)
      
  phase.shell_path = "/bin/sh"
  phase.shell_script = EXPORT_ENV_PHASE_SCRIPT
  phase.show_env_vars_in_log = '0'

end

the xcode version is 6.4

i don't know what you mean in local pod i just follow the document to run the examples of Masonry

**Comment by robertjpayne** [comment]
@AliOmari you should be able to just add `pod 'Masonry', '~> 0.6.2'`?

**Comment by AliOmari** [comment]
@robertjpayne where to add this line ??
do u mean replacing pod 'Masonry', :path => './' with pod 'Masonry', '~> 0.6.2'  ??

**Comment by robertjpayne** [comment]
@AliOmari I strongly recommend having a read over at cocoapods.org but your entire podfile should look something like:

```
platform :ios, '7.0'

pod 'Masonry', '~> 0.6.2'
```

And of course any other pods you like.

**Comment by AliOmari** [comment]
@robertjpayne thanks for your advice
but i don't wrote this pod file, i just found it in the repo and i just install it

**Comment by robertjpayne** [comment]
@AliOmari yea I noticed! Sorry again that Podfile in the root repo is for the Masonry project, not intended for others to use in their own projects. It's just so Travis continuous integration can test that our Podspec is valid.

**Comment by AliOmari** [comment]
aha okay @robertjpayne i did't understand this in that way.
actually i'm not professional i'm just beginner in iOS development and trying to integrate Masonry into my project.
really thanks @robertjpayne  i appreciate it

**Comment by robertjpayne** [comment]
@AliOmari no worries! Yea I'd have a look on `cocoapods.org` a wealth of good pods there to help you get started, but try not to just grab a pod for everything too, it's good to learn the basics.

Also if you're just starting off I'd recommend skipping Objective-C and diving straight into swift and using `SnapKit` our Swift port instead :+1:

**Comment by chenjiang3** [comment]
when i run pod install , it has some exception, who can help me?
pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `Masonry` from `./`
Downloading dependencies
Installing Expecta 1.0.5 (was 1.0.0)
Installing Masonry 0.6.3 (was 0.6.1)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

[!] Failed to find 'Pods-MasonryTestsLoader-Masonry' target

/Users/chenjiang/Documents/github/Masonry/Podfile:30:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile.rb:170:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile.rb:170:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:806:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:794:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:793:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:158:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by soberman** [comment]
I am having the same issue.
