### ISSUE TITLE
A strange Bug of UIButton

### ISSUE THREAD

**Issue by wy19901227** [SnapKit/Masonry#239]
when I set a UIButton's MASConstraint of height, ant set it deactive. But  the Button will not deactive,It's heigth will be 31. I do not know why.  both your method and apple's method.

**Comment by wy19901227** [comment]
I chage the code in your demo of update,you can do it.


   [self.growinButton1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(CGPointMake(100, 100));
        make.width.equalTo(@(100)).priorityLow();
     self.h= make.height.equalTo(@(100));
        make.width.lessThanOrEqualTo(self);
       //  make.height.lessThanOrEqualTo(self);
        
        
    }];
    self.growinButton1.backgroundColor=[UIColor greenColor];

   [self.h deactivate];

**Comment by robertjpayne** [comment]
Deactivating constraints don't cause them to "unapply" it just means they wont further affect the layout calculations. It's like setting `self.frame.size.height = 50.0` once it's set it'll remain like that until something else alters in.
