### ISSUE TITLE
hi,about MASLayoutConstraint.

### ISSUE THREAD

**Issue by wy19901227** [SnapKit/Masonry#240]
In MASViewConstrain, can you make the MASLayoutConstraint property public? Becasule, I want to get the constant .

**Comment by wizzardchao** [comment]
@wy19901227 , in fact, MASLayoutConstraint is a subclass of NSLayoutConstraint, you can access all the properties.
And as objective-c is a dynamic language, you can access any property even it's private.

**Comment by wy19901227** [comment]
yeh, I can get it by KVC ,I just think make it public will be better.

**Comment by cloudkite** [comment]
Exposing constant is difficult since under the hood constraints built using MASConstraintMaker are wrapped in either MASViewConstraint or MASCompositeContraint. The later can't return a meaningful constant
