### ISSUE TITLE
iOS 9 Background Thread issue

### ISSUE THREAD

**Issue by MikeDyna** [SnapKit/Masonry#241]
Hi,

first of all, i love this library. I use it everyday and it makes Auto-Layout so much less painful.

Since the release of iOS 9 i get following message in the log:
"This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release."

You can get rid of this with using GCD and putting the Masonry code in dispatch_async(dispatch_get_main_queue(), ^{
   // do work here
});

Is this gonna be fixed in the Obj-C version or is the support for iOS 9 not guaranteed?

cheers

**Comment by cloudkite** [comment]
Hi are you modifying your views in a background thread? You should do all UI work in the main thread, UIKit may crash otherwise

**Comment by robertjpayne** [comment]
Feel free to re-open if you are indeed running on the main thread and this is still crashing.
