### ISSUE TITLE
How to use Masonry layout some views with same space?

### ISSUE THREAD

**Issue by hellometers** [SnapKit/Masonry#244]
Hi, I have some views with known  width in my project, I want layout these views with same space:

![iphone](https://cloud.githubusercontent.com/assets/1685497/10010604/330c38e8-6120-11e5-8510-b0794b728be5.png)
 
I could add some "placeholder views" with same width as these empty space , but is there any other  solutions? 

Thanks a lot :)
![iphone2](https://cloud.githubusercontent.com/assets/1685497/10010626/92e7b616-6120-11e5-9957-853ce04c7855.png)

**Comment by robertjpayne** [comment]
Please try to use StackOverflow for future help requests, this isn't the best place to do it.

Regardless you want to do something like `make.left.equalTo(otherView.mas_right).offset(50)`

Cheers
