### ISSUE TITLE
In iOS9 Masonry collapse

### ISSUE THREAD

**Issue by wangweijia** [SnapKit/Masonry#245]
Masonry working very well on ios 8.4 ,but when I running my APP on iOS9,APP collapse by Masonry...T.T

**Comment by robertjpayne** [comment]
Please if you're going to open issues provide more information about what is going wrong and respect the contributors by not adding superfluous 'T.T' remarks.

Feel free to open a new issue with more information that could help us resolve any bugs.

**Comment by wy19901227** [comment]
就是，提问题就提问题，卖什么萌？什么信息也不给作者，让别人自己写demo调试，改完bug告诉你可以用了？真是懒！！！

发自我的 iPhone
