### ISSUE TITLE
Add prebuilt framework for Carthage

### ISSUE THREAD

**Issue by dcaunt** [SnapKit/Masonry#246]
Can I request that a prebuilt framework be added to the 0.6.3 release for Carthage?

This would require you to run the following and attach the resulting Masonry.framework.zip to the release on GitHub:

```
git checkout v0.6.3
carthage build --no-skip-current --verbose
carthage archive Masonry
```

Alternatively I can build the zip and provide it for you to attach if that's helpful. Thanks.

**Comment by robertjpayne** [comment]
@dcaunt Does carthage support zipping the dsym in the framework now? Masonry compiles really quickly and I don't see much value in doing this and maintaining it for every release.

**Comment by dcaunt** [comment]
It does indeed support zipping the dSYM now, since version 0.9 iirc. 

I don't think it is much work to add the zip but appreciate that it's your call. I couldn't see a discussion of this in an existing issue so I thought I'd raise it.

**Comment by robertjpayne** [comment]
@dcaunt I'm going to pass for now, as I am with SnapKit too. I don't have an easy build pipeline right now and it also starts to get messy once people ask for Bitcode etc…

**Comment by dcaunt** [comment]
Fair enough – thanks for addressing this.
