### ISSUE TITLE
iOS 9 Auto-Layout Background Thread issue

### ISSUE THREAD

**Issue by MikeDyna** [SnapKit/Masonry#248]
Since i installed Xcode 7 with iOS9 i get this exception for all my Masonry layouted views:

"This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release."

In lengthy TableViews this even slows down the UI Thread!

You can work around this issue with GCD:
dispatch_async (dispatch_get_main_queue(), ^{
          (masonry layout code)
    });

Will this be fixed in the maintenance version for Obj-C?

**Comment by robertjpayne** [comment]
@MikeDyna hi this isn't an issue with Masonry. Somewhere in your code you are calling from a background thread something that would create constraints. I'd add some break points and backtrack where the background thread call is initiated.

**Comment by MikeDyna** [comment]
Thx for the quick answer. I will check my threading. 
Without Masonry, layout would be way less fun! ;)

**Comment by robertjpayne** [comment]
Closing this for now, please re-open if you feel it's not resolved and you are certain you are not calling Masonry from a background thread.
