### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by tospery** [SnapKit/Masonry#249]
UIView *aaa = [[UIView alloc] init];
    aaa.backgroundColor = [UIColor redColor];
    [self.view addSubview:aaa];
    [aaa mas_makeConstraints:^(MASConstraintMaker *make) {
        make.height.equalTo(@44);
        make.width.equalTo(@100);
        make.centerY.equalTo(self.view);
        make.centerX.equalTo(self.view).multipliedBy(1/3);
    }];

**Comment by tospery** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    UIView *aaa = [[UIView alloc] init];
    aaa.backgroundColor = [UIColor redColor];
    [self.view addSubview:aaa];
    [aaa mas_makeConstraints:^(MASConstraintMaker *make) {
        make.height.equalTo(@44);
        make.width.equalTo(@100);
        make.centerY.equalTo(self.view.mas_centerY);
        make.centerX.equalTo(self.view.mas_centerX).multipliedBy(1/3);
    }];
}
    crash also

**Comment by billychen2014** [comment]
remove your code "make.centerX.equalTo(self.view).multipliedBy(1/3);", that's will be ok!

**Comment by robertjpayne** [comment]
@tospery mind elaborating on what the crash is exactly?

**Comment by cloudkite** [comment]
@tospery you can only do multipliedBy on width or height. This is a limitation of Auto Layout

**Comment by tospery** [comment]
thanks all
