### ISSUE TITLE
Don't recommend using SnapKit?

### ISSUE THREAD

**Issue by tonyarnold** [SnapKit/Masonry#250]
I realise this code isn't maintained anymore, but recommending SnapKit without mentioning that it can't be used from Objective-C isn't great.

**Comment by robertjpayne** [comment]
@tonyarnold it's totally maintained, we're still accepting PR's and fixing bugs. We're just not adding new features such as iOS 9's layout anchors unless someone creates a good PR to do so.

@cloudkite is really busy these days and I am as well so we're focusing new feature efforts on the swift repo!

I still use Masonry in all my Objective-C projects.

**Comment by tonyarnold** [comment]
Oh great! The warning made it sound like Masonry had been replaced, and I should be looking at SnapKit. I'm still using it in a number of projects. 

Definitely understand about busy-ness and maintaining projects ;)

**Comment by cloudkite** [comment]
@tonyarnold yeah sorry notice sounds scarier than it is! How would you word it?

**Comment by tonyarnold** [comment]
Maybe something like:

"Masonry is in a bugfix only state, as more developers will be moving to Swift. If you're using Swift in your project, we recommend using SnapKit as it provides better type safety with a simpler API. Objective-C projects should stick with Masonry."

**Comment by cloudkite** [comment]
@robertjpayne, @tonyarnold how about?

"Masonry is still actively maintained, we are committed to fixing bugs and merging good quality PRs from the wider community. However if you're using Swift in your project, we recommend using SnapKit as it provides better type safety with a simpler API."

**Comment by tonyarnold** [comment]
:+1: Reads well, I like it
