### ISSUE TITLE
gmgridview library not working any more ! scroll view library

### ISSUE THREAD

**Issue by AliOmari** [SnapKit/Masonry#252]
this library need this line of code 
_gmGridView.autoresizingMask = UIViewAutoresizingFlexibleWidth |      UIViewAutoresizingFlexibleHeight;
and since i'm using autolayout this line become not valid anymore.
what can i do to make it work with masonry constraints ?!

**Comment by robertjpayne** [comment]
@AliOmari please post this issue on gmgridview's issue tracker as it's their issue to support Auto Layout and not inversely nothing we can do about it.
