### ISSUE TITLE
When use Masonry in ".mm" file, it will conflict with the keyword "and" of C++.

### ISSUE THREAD

**Issue by DiveinEdu** [SnapKit/Masonry#254]

**Comment by k06a** [comment]
Try this:
```
#define and end
#import <Masonry/Masonry.h>
#undef and
```
 
:)

**Comment by robertjpayne** [comment]
Unfortunately Masonry at this point has too many projects that would break if we were to remove this keyword and it's only an issue for Objective-C++. For this I recommend making a fork or using k06a's recommendation.
