### ISSUE TITLE
Compatiblity issue with Masonry and iOS 9

### ISSUE THREAD

**Issue by TheNightbear** [SnapKit/Masonry#256]
Since I've started to build my app with Xcode 7.01 the app fails to run on iOS 9.

The following use of Masonry 
```
    UIView* contentView = UIView.new;
    [self.vScrollView addSubview:contentView];
    [contentView makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.vScrollView); 
        make.width.equalTo(self.centralView.width); 
    }];
```
lets my application crash:

```
2015-10-10 01:46:10.381 MyApp[7575:686159] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempting to add unsupported attribute: (null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x04514a94 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x03fd5e02 objc_exception_throw + 50
	2   CoreFoundation                      0x0451492a +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x016743e6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   MyApp                               0x0014395a -[MASViewConstraint setSecondViewAttribute:] + 746
	5   MyApp                               0x00144abe __40-[MASViewConstraint equalToWithRelation]_block_invoke + 2110
	6   MyApp                               0x0013c78d __24-[MASConstraint equalTo]_block_invoke + 125
	7   MyApp                               0x00106acb __41-[CatalogViewController viewDidLoad]_block_invoke158 + 411
	8   MyApp                               0x0014c527 -[UIView(MASAdditions) mas_makeConstraints:] + 167
	9   MyApp                               0x0012adf5 -[UIView(MASShorthandAdditions) makeConstraints:] + 85
	10  MyApp                               0x0010603a -[CatalogViewController viewDidLoad] + 906
	11  UIKit                               0x0241cd74 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 44
	12  UIKit                               0x024218c2 -[UIViewController loadViewIfRequired] + 1556
	13  UIKit                               0x02421cf1 -[UIViewController view] + 35
	14  MyApp                               0x0012f4e5 -[ECSlidingViewController viewDidLoad] + 245
	15  UIKit                               0x0241cd74 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 44
	16  UIKit                               0x024218c2 -[UIViewController loadViewIfRequired] + 1556
	17  UIKit                               0x02421cf1 -[UIViewController view] + 35
	18  UIKit                               0x022d4ccc -[UIWindow addRootViewControllerViewIfPossible] + 69
	19  UIKit                               0x022d53fd -[UIWindow _setHidden:forced:] + 324
	20  UIKit                               0x022d579d -[UIWindow _orderFrontWithoutMakingKey] + 49
	21  UIKit                               0x022e8b64 -[UIWindow makeKeyAndVisible] + 81
	22  UIKit                               0x02256b70 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4190
	23  UIKit                               0x0225dec6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1976
	24  UIKit                               0x02281905 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3171 + 68
	25  UIKit                               0x0225abae -[UIApplication workspaceDidEndTransaction:] + 163
	26  FrontBoardServices                  0x06370ccc __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2 + 71
	27  FrontBoardServices                  0x063707a3 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 54
	28  FrontBoardServices                  0x0638e1cb -[FBSSerialQueue _performNext] + 184
	29  FrontBoardServices                  0x0638e602 -[FBSSerialQueue _performNextFromRunLoopSource] + 52
	30  FrontBoardServices                  0x0638d8fe FBSSerialQueueRunLoopSourceHandler + 33
	31  CoreFoundation                      0x0442ee7f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	32  CoreFoundation                      0x04424b0b __CFRunLoopDoSources0 + 523
	33  CoreFoundation                      0x04423f28 __CFRunLoopRun + 1032
	34  CoreFoundation                      0x04423866 CFRunLoopRunSpecific + 470
	35  CoreFoundation                      0x0442367b CFRunLoopRunInMode + 123
	36  UIKit                               0x0225a497 -[UIApplication _run] + 540
	37  UIKit                               0x0225fcc1 UIApplicationMain + 160
	38  MyApp                               0x000cc7da main + 138
	39  libdyld.dylib                       0x05f1aa21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

What can I do to (temporarly or better permanently) solve the issue?

As far as I have understood, there is a compatiblity issue with Masonry and iOS 9.
Is this correct? If yes, what is your timeline to be compatible to iOS 9?

**Comment by robertjpayne** [comment]
@TheNightbear does this compile against iOS 8? it's hard to say with just the code snippet you've provided, do you have a few more lines you can share?

Specifically would be good to see the entire `[CatalogViewController viewDidLoad]` method.

**Comment by TheNightbear** [comment]
@robertjpayne it does, but unfortunately it's crashing on iOS 8 & 9 at line
```
make.width.equalTo(aView.width);
```
or
```
make.height.equalTo(aView.height);
```
It allways ends up with an invalid secondViewAttribute of value nil. 

If I set the "pure value" it works (does not crash):
```
           make.width.equalTo(@(aView.frame.size.width));
```
This is not a valid workaround, because it will not work dynamically if the size of the source view changes (which happens in my case). 

As temporarly workaround I use

for "width"
```
make.left.equalTo(aView.left);
make.right.equalTo(aView.right);
``` 
and for "height"
```
make.top.equalTo(aView.bottom);
make.bottom.equalTo(aView.bottom);
``` 

So the question is, where is the difference between the MASViewAttribute returned from view.height and view.width versus the one returned from view.top / view.bottom / view.left / view.right? 
Because the first two will trigger the assertion in the "setSecondViewAttribute" method.

**Comment by robertjpayne** [comment]
@TheNightbear again would be really useful to see the whole code method rather than snippets pulled out.

The reason there are no second attributes for the `width` and `height` attributes is that they are self constraints so to speak and are added directly to the view without a toItem or toAttribute.

If you do a `NSLog(@"%@", aView.width)` what do you get? Just trying to eliminate what may be causing it but this is definitely something specific to your project if it's crashing in iOS 8 because we'd have many many many more reports otherwise!

**Comment by TheNightbear** [comment]
@robertjpayne while I was creating some log outputs I observed a difference in behavior if I call ```make.width.equalTo(aView.width)```:

1. The UIView created via the Interface Builder is crashing if I call the .width attribute in `NSLog(@"%@", aView.width)` -->  `EXC_BAD_ACCESS (code=1, address=0x43a00000)`

2. A UIView (or similar class like UIScrollView) created and attached to a parent view in the `viewDidLoad` method returns `null` and triggers the `'NSInternalInconsistencyException', reason: 'attempting to add unsupported attribute: (null)'` in `setSecondViewAttribute` method.

---
Btw. I found an example in https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleScrollView.m at line 49. It's using

```make.width.equalTo(self.scrollView);``` instead of 
```make.width.equalTo(self.scrollView.width);``` .

The same is valid for the height attribute:
```make.height.equalTo(leftScrollHint);``` instead of 
```make.height.equalTo(leftScrollHint.height);``` .

I tried both approaches in my code and it works! 
**But is it the right way?**

---
Here's the whole code of the method:

```objective-c
- (void)viewDidLoad
{
    [super viewDidLoad];
    [self.slidingViewController setAnchorRightRevealAmount:270.0f];
    
    //prepare status bar
    _hideStatusBar = NO;
    [self setNeedsStatusBarAppearanceUpdate];
    
    _enlargedRow = -1;

    _vScrollView = UIScrollView.new;
    [self.centralView addSubview:_vScrollView];
     [_vScrollView makeConstraints:^(MASConstraintMaker *make) {
          make.edges.equalTo(self.centralView);
     }];
    [_vScrollView setDelegate:self];

    UIView* contentView = UIView.new;
    [_vScrollView addSubview:contentView];
    
    NSLog(@"%@", _vScrollView);
    NSLog(@"%@", _vScrollView.width);

    NSLog(@"%@", contentView);
    NSLog(@"%@", contentView.width);
    
    NSLog(@"%@", _centralView);
    //NSLog(@"%@", _centralView.width); // --> triggers EXC_BAD_ACCESS exception
    
     [contentView makeConstraints:^(MASConstraintMaker *make) {
         make.edges.equalTo(_vScrollView);
         //make.width.equalTo(_centralView.width); // --> triggers EXC_BAD_ACCESS exception
         make.width.equalTo(_centralView); // --> works!
       }];

    [self loadCatalog];
    
    UIView *lastView;
    CGFloat height = 85;
    for (int i = 1; i <= [_catalogRows count]; i++) {
        UIView *view = UIView.new;
        view.tag = i*1000; //row id
        [contentView addSubview:view];
        
       [view makeConstraints:^(MASConstraintMaker *make) {
           make.top.equalTo(lastView ? lastView.bottom : @0);
            make.left.equalTo(contentView.left);
                
            NSLog(@"%@", contentView);
            NSLog(@"%@", contentView.width); // --> output "(null)"
            //make.width.equalTo(contentView.width); // --> triggers crash in "setSecondViewAttribute"
            make.width.equalTo(contentView); // --> works!
                
            make.height.equalTo(@(height));
        }];
               
        //add Subview + content
        [self createHorizontalScrollView:view rowData:_catalogRows[i-1]];
        lastView = view;
    }

    [contentView makeConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(lastView.bottom); 
    }];
    
    _adView = [[MPAdView alloc] initWithAdUnitId:@"********************************"
                                            size:MOPUB_BANNER_SIZE];
    _adView.delegate = self;
    _adView.frame = CGRectMake((_adContainer.bounds.size.width - MOPUB_BANNER_SIZE.width) / 2,
                                   _adContainer.bounds.size.height - MOPUB_BANNER_SIZE.height,
                                   MOPUB_BANNER_SIZE.width, MOPUB_BANNER_SIZE.height);
    [_adContainer addSubview:_adView];
    [_adView loadAd];
    
    //Show help
    [self showHelp];
}
```

**Comment by robertjpayne** [comment]
@TheNightbear do you have any other 3rd party libs integrated with your project? What if you try NSLog(@"%@", otherView.mas_width). An EXEC_BAD_ACCESS on a NSLog like that normally indicates you're attempting to NSLog a non-objectc object. In this case if `.width` is from a 3rd party library and a CGFloat it would probably be zero and thus the "null" attribute but crashing log statement.

**Comment by robertjpayne** [comment]
@TheNightbear or if you can just in Xcode when autocomplete pops-up for `.width` what type is it? It really seems in this case it's not a `MASViewAttribute` which it should be.

**Comment by TheNightbear** [comment]
@robertjpayne yes, I have other 3rd party libs in my project. But none of them is (officially) dealing with UIViews.

Here are the results of using `mas_width` instead of `width`:

1. On the UIView with the EXC_BAD_ACCESS exception the result is this: ![_centralview](https://cloud.githubusercontent.com/assets/8239167/10468403/2e9dba62-71ff-11e5-9c21-9c7e8981a02f.png)

2. On other UIViews `mas_width` returns a valid object of type `MASViewAttribute` while `.width` returns `null`.

In any case the autocomplete pop-up shows a MASViewAttribute for `.width`: 
![code_completion](https://cloud.githubusercontent.com/assets/8239167/10468759/20771076-7201-11e5-89c9-c26ed254f7b7.png)

**Comment by robertjpayne** [comment]
@TheNightbear and just to make sure you have `MAS_SHORTHAND` turned on via preprocessor macros?

It's really strange if the `mas_XXXX` shortcuts work so should the non prefixed if MAS_SHORTHAND is defined.

**Comment by TheNightbear** [comment]
@robertjpayne yes it's turned on by this two lines in my .pch file:

```objective-c
#define MAS_SHORTHAND
#import "Masonry.h"
```

**Comment by robertjpayne** [comment]
@TheNightbear tough to say without having the full project source, Ultimately up to you if you want to share that robertpayne [at] me [dot] com.

Otherwise, I'd recommend using the full version extensions `mas_*`.

**Comment by cloudkite** [comment]
@robertjpayne @TheNightbear I think it would be worth doing a text search across all your libraries and code to see if there isn't another category that also extends `UIView` with `width`, 'height', `left` etc. 

I dont think autocomplete is not a guarantee of what the category property will be at runtime. Because categories can override each other depending on the order they are imported

**Comment by TheNightbear** [comment]
@cloudkite sounds reasonable to me to check the libraries. 
The last run of `pod update` might have added this sideeffect to the project.
I will let you know, if I find something.

@robertjpayne unfortunatly I'm not allowed to share the full project code. But thank you for your offer to help me with a deeper inspection!

**Comment by badgercl** [comment]
Hi!

I'm posting here since the bug seems to be the same.

I'm a new Masonry user since another lib I started using needs your lib. 
I started copying the examples from the other lib using Masonry and I got several compile-time issues.
After some research on the errors, I noticed the compile-time issues go away when by adding the mas_ prefix.

It seems the ```#define MAS_SHORTHAND``` (included in my .pch file) somehow is not working.
I'm sure my .pch file is used at compile-time since have defined other macros.

**Comment by TheNightbear** [comment]
@cloudkite @robertjpayne I was able to identifiy the responsible library: [mopub-ios-sdk] (https://github.com/mopub/mopub-ios-sdk) 

The library is compatible up to version 3.13.0. 
With the latest update to version 4.0.0 ([Changelog](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md)) they added: 
```objective-c
@property (nonatomic) CGFloat height;
@property (nonatomic) CGFloat width;
```
in 
[UIView+MPAdditions.h](https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/Internal/Utility/Categories/UIView%2BMPAdditions.h)
[UIView+MPAdditions.m](https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/Internal/Utility/Categories/UIView%2BMPAdditions.m)

**Any idea how to solve this issue** (without using *mas_* prefix)**?**

**Comment by cloudkite** [comment]
Last category loaded wins, so you could in theory import Masonry after mopub.





You might want to check ur compile flags I think the linker flag 'all_load' might possibly interfere with load order.




Even if this works you could end up breaking mopub functionality.




Best solution would be for Mopub to prefix their categories, libraries shouldn't use unprefixed categories unless the dev opts-in. Plus these are internal methods so there's no reason to have them unprefixed

**Comment by EricJones89** [comment]
To add a little context to this issue I am having similar yet different issues MAS_SHORTHAND. I am importing the framework using Carthage. In order for XCode to be happy with the framework import I had to add it to the embedded binaries. After this I was able to import <Masonry/Masonry.h> without an issue and use the mas_* syntax. 

I really prefer the shorthand syntax so I tried adding the MAS_SHORTHAND definition. No dice. After tinkering for a while I was able to get the compiler to be happy after adding a build flag of MAS_SHORTHAND. This would crash at runtime, however, with an unrecognized selector error.

Currently I have not been able to get the shorthand version to work with the compiler and not crash at runtime. For context I am not using a pch file.

**Comment by robertjpayne** [comment]
@TheNightbear unfortunately there is nothing we can really do to help you resolve this, the other library *should not* be such a poor sport and have unprefixed categories.

@EricJones89 likewise nothing we can do to help you if you're using Carthage, the MAS_SHORTHAND define must be present as the code is compiled, and Carthage compiles the frameworks *before* they are integrated into the project so your MAS_SHORTHAND macro does nothing, or in some cases may make the header seem valid but the underlying binary code will always be invalid.

Please just use `mas_`, it may be a bit uglier but trust me it'll save you headache in the long run. Swift is headed in this direction too as we can't even use a macro to try and shorthand categories.

Sorry there isn't better solutions to this, it's really the limitations of Objective-C/Xcode.

**Comment by xiaoliuTx** [comment]
I think you should put the Masonry code in viewDidAppear: method. That's solve my problem.

**Comment by a-radwan** [comment]
Make sure the `vScrollView` is not null.
 If the container is null, this crash will happen.

**Comment by bstillitano** [comment]
I just want to add to this:

I was getting this error when calling
`make.edges.equalTo(self)`

Once i changed it to `make.edges.equalTo(self.view)` it began working. Simple oversight.
