### ISSUE TITLE
"libPods-Masonry iOS Examples.a"this file in xcode is red

### ISSUE THREAD

**Issue by gleeeli** [SnapKit/Masonry#258]
xcode error is:
Ld /Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Products/Debug-iphonesimulator/Masonry\ iOS\ Examples.app/Masonry\ iOS\ Examples normal x86_64
    cd /Users/mac02/Downloads/Masonry-master/Examples
    export IPHONEOS_DEPLOYMENT_TARGET=6.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Products/Debug-iphonesimulator -F/Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Products/Debug-iphonesimulator -filelist /Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Intermediates/Masonry\ iOS\ Examples.build/Debug-iphonesimulator/Masonry\ iOS\ Examples.build/Objects-normal/x86_64/Masonry\ iOS\ Examples.LinkFileList -mios-simulator-version-min=6.1 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lPods-Masonry\ iOS\ Examples-Masonry -framework Foundation -framework UIKit -fobjc-arc -fobjc-link-runtime -framework UIKit -framework Foundation -framework CoreGraphics -lPods-Masonry\ iOS\ Examples -Xlinker -dependency_info -Xlinker /Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Intermediates/Masonry\ iOS\ Examples.build/Debug-iphonesimulator/Masonry\ iOS\ Examples.build/Objects-normal/x86_64/Masonry\ iOS\ Examples_dependency_info.dat -o /Users/mac02/Library/Developer/Xcode/DerivedData/Masonry_iOS_Examples-apkfwsucgztejvgidvmepozlvqjl/Build/Products/Debug-iphonesimulator/Masonry\ iOS\ Examples.app/Masonry\ iOS\ Examples

ld: library not found for -lPods-Masonry iOS Examples-Masonry
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gleeeli** [comment]
I download many times ,but still have this issue when run the Masonry iOS Examples

**Comment by 347008893** [comment]
I have the same problem and how to solve the problem

**Comment by cloudkite** [comment]
please try deleting `podfile.lock` and `pods` folder and rerunning `pod install`
