### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attributes should be chained before defining the constraint relation'

### ISSUE THREAD

**Issue by hanhailong** [SnapKit/Masonry#259]
-(instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    if (self == [super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        //TODO
        UIView *backgroundView = [UIView new];
        [self.contentView addSubview:backgroundView];
        
        [backgroundView addSubview:self.firstView];
        [backgroundView addSubview:self.secondView];
        [backgroundView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.size.equalTo(self.contentView);
            make.center.equalTo(self.contentView);
        }];
        
        [self.firstView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.mas_equalTo(backgroundView.mas_centerY);
            make.left.equalTo(backgroundView.mas_left);
            make.right.equalTo(self.secondView.mas_left).with.offset(-5);
            make.height.mas_equalTo(@150);
            make.width.equalTo(self.secondView);
        }];
        
        [self.secondView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.mas_equalTo(backgroundView.mas_centerY);
            make.left.equalTo(self.firstView.mas_right).width.offset(5);
            make.right.equalTo(backgroundView.mas_right);
            make.height.mas_equalTo(@150);
            make.width.equalTo(self.firstView);
        }];
        
    }
    return self;
}

The above is my code, please help me to look at have what problem

**Comment by hanhailong** [comment]
My fault, code wrong, here I'm very sorry！！！Zhe code is "      make.left.equalTo(self.firstView.mas_right).width.offset(5);" Should be with, rather than the width

**Comment by swif2** [comment]
@hanhailong  I mistyped too. Thanks!
