### ISSUE TITLE
is masonry will support NSLayoutConstraint's active?

### ISSUE THREAD

**Issue by coolgo** [SnapKit/Masonry#263]
when read the method of autoloyout ,i see that
 - (void)addConstraint:(NSLayoutConstraint *)constraint NS_AVAILABLE_IOS(6_0); // This method will >be deprecated in a future release and should be avoided.  Instead, set NSLayoutConstraint's active property to YES.
but  i did't see the related future in the masonry，so is masonry will support NSLayoutConstraint's active?

**Comment by cloudkite** [comment]
active is already supported. please see https://github.com/SnapKit/Masonry/blob/4acafbda6ece5ec0fe4ebe4c6af5e87211666861/Masonry/MASViewConstraint.m#L290
