### ISSUE TITLE
UITableViewCell & min-height

### ISSUE THREAD

**Issue by poledeveloper** [SnapKit/Masonry#264]
Hi! I have an "how-to question"

I have this UITableView (picture 1) with the following code
![1](https://cloud.githubusercontent.com/assets/6029717/10858123/eafe261e-7f52-11e5-97a9-7e5a6717206d.png)

<img width="837" alt="cell_code" src="https://cloud.githubusercontent.com/assets/6029717/10858128/ee40af86-7f52-11e5-9597-9b0defafdc9a.png">

If i add a long text to label everything works correctly without heightforrowatindexpath delegate.
![2](https://cloud.githubusercontent.com/assets/6029717/10858186/609e9c28-7f53-11e5-94ff-0425f7010e36.png)

If i remove a greaterThanOrEqualTo constraint to cell contentview this is result and it's correct.
![3](https://cloud.githubusercontent.com/assets/6029717/10858216/a09c10f8-7f53-11e5-8add-f69907f0ffac.png)

But how can I get the following result that I got by commenting line 41? I must to keep a min-height of the UITableViewCell but "lblDescrizione" must fit to its content if not exceeds the min-height..
![4](https://cloud.githubusercontent.com/assets/6029717/10858404/0d82c47c-7f55-11e5-8032-e135bb89e62b.png)

Thank you very much

**Comment by cloudkite** [comment]
Theres quite a few different approaches you can take to make this work.

please have a look at:
http://www.raywenderlich.com/73602/dynamic-table-view-cell-height-auto-layout
http://imnotyourson.com/uitableviewcell-dynamic-height-with-autolayout-conclusion/
http://useyourloaf.com/blog/table-view-cells-with-varying-row-heights.html
http://www.raizlabs.com/dev/2014/02/leveraging-auto-layout-for-dynamic-cell-heights/

some of these examples are using interface builder but the same principles apply.

**Comment by poledeveloper** [comment]
thank you very much Jonas
