### ISSUE TITLE
attempting to add unsupported attribute

### ISSUE THREAD

**Issue by AliOmari** [SnapKit/Masonry#266]
i got this when i'm trying to make constraints on uiviewcontroller.view and i check if it has super view or not but i add this to the rootviewcontroller
[self addChildViewController:viewController];
 [self.view addSubview:viewController.view];

i really don't understand why this happens

**Comment by cloudkite** [comment]
Can you explain what error you are seeing and post code from your rootViewController and viewController. Otherwise can't really deduce much from those two lines
