### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by fragno** [SnapKit/Masonry#270]
COV_TARGET_NAME = "Pods-MasonryTestsLoader-Masonry" can not pod install success，should be
Pods-MasonryTestsLoader

**Comment by robertjpayne** [comment]
@fragno can you please share your Podfile?

**Comment by fragno** [comment]
post_install do |installer|

COV_TARGET_NAME =  *"Pods-MasonryTestsLoader"*
EXPORT_ENV_PHASE_NAME = "Export Environment Vars"
EXPORT_ENV_PHASE_SCRIPT = "export | egrep '( BUILT_PRODUCTS_DIR)|(CURRENT_ARCH)|(OBJECT_FILE_DIR_normal)|(SRCROOT)|(OBJROOT)' > $SRCROOT/../script/env.sh"

# find target
classy_pods_target = installer.pods_project.targets.find{ |target| target.name == COV_TARGET_NAME }
unless classy_pods_target
raise ::Pod::Informative, "Failed to find '" << COV_TARGET_NAME << "' target"
end
