### ISSUE TITLE
Support easy view containment

### ISSUE THREAD

**Issue by benjohnbarnes** [SnapKit/Masonry#276]
The introduction gives the example `make.edges.equalTo(superview).insets(UIEdgeInsetsMake(5, 10, 15, 20))`

As far as I can see, there is no short form (single line) to achieve containment of a view. Ie – having the constrained view's edges be up to, but not outside of, another view (with optional insets).

The syntax for this might look like: `make.edges.limitedInside(superview).insets(UIEdgeInsetsMake(5, 10, 15, 20))`.

**Discussion**
Containment is not the same as `make.edges.greaterThan(superview).insets(UIEdgeInsetsMake(5, 10, 15, 20))`. 

* The `greaterThan` operator limits of the left most and top most extreme of the attributes.
* The `lessThan` operator limits the right most and bottom most extreme of the attributes.

The envisaged `limitedInside` operator will constrain the left and top attribute to be greater than, and the right and bottom attribute to be less than.

For `centre` and `size`, `limitedInside` could provide sensible functions.

---

There could be a corresponding `limitedOutside` operator, although I've not had a need for this yet.

Possibly I've missed something, and this is in fact achievable, in which case I'd love to know how to do it!

Thanks.

**Comment by cloudkite** [comment]
@benjohnbarnes 

What you have described:
> The greaterThan operator limits of the left most and top most extreme of the attributes.
> The lessThan operator limits the right most and bottom most extreme of the attributes.

Can be written as:
```
make.left.top.greaterThanOrEqualTo(superview).insets(UIEdgeInsetsMake(5, 10, 15, 20))
make.right.bottom.lessThanOrEqualTo(superview).insets(UIEdgeInsetsMake(5, 10, 15, 20))
```

Hope that helps

**Comment by cloudkite** [comment]
Thanks for the suggestion though! While it's tempting to add various convenience functions like `limitedInside`, `limitedOutside` etc. We try to only to only provide the basic building blocks. This keeps the API lightweight and easier to understand.

**Comment by k06a** [comment]
Nice suggestion :+1:

**Comment by robertjpayne** [comment]
Closing as the best response to this is to make your own additions to Masonry's core API. We're trying to keep the API to building blocks.
