### ISSUE TITLE
Add `margins` to `MASConstraintMaker`

### ISSUE THREAD

**Issue by benjohnbarnes** [SnapKit/Masonry#277]
`MASConstraintMaker` has `edges` providing a `MASCompositeContraint`. It would be nice to have a similar `margins` property.

As a work around, I think this is something client code can achieve cleanly with a category.

**Comment by cloudkite** [comment]
@benjohnbarnes Can you please explain how `margins` would differ from `edges`?

**Comment by k06a** [comment]
@cloudkite maybe @benjohnbarnes means use `leading` and `trailing` inside `margins` instead of `left` and `right`.

**Comment by benjohnbarnes** [comment]
Hi, sorry for a very late reply on this…

So, `MASConstraintMaker` implement `edges` thus:

    - (MASConstraint *)edges {
        return [self addConstraintWithAttributes:MASAttributeTop | MASAttributeLeft | MASAttributeRight | MASAttributeBottom];
    }

I am suggesting adding in `margins`, which would be implemented:

    - (MASConstraint *)margins {
        return [self addConstraintWithAttributes:MASAttributeTopMargin | MASAttributeLeftMargin | MASAttributeRightMargin | MASAttributeBottomMargin];
    }

… as noted, this is easy enough for client code to implement with a category.

**Comment by robertjpayne** [comment]
@benjohnbarnes this is an issue in the Swift library SnapKit too, it's going to be difficult to match margins against edges.

**Comment by robertjpayne** [comment]
Closing this as it's actually resolved, but work still needs to be done for #324
