### ISSUE TITLE
Problem with  boxes layout  after re-sizing of window

### ISSUE THREAD

**Issue by arifhussain353** [SnapKit/Masonry#278]
Hi, 
  I have one issue with my layout boxes after re-sizing of window on menu-toggle button click.For quick explanation i am including two images
Before click on toggle button ( first time on load page) =
http://prntscr.com/94in5b
After click on toggle button =
http://prntscr.com/94inkq
Even i click back on toggle button still layout problem, here is image 
http://prntscr.com/94inxd

My code
 (html )
```javascript
 <div class="col-md-12 onetime-content ">
    <div class="col-md-3 ontime-box ">......</div>
</div>
```
(Javascript)
```javascript
var container = jQuery('.onetime-content');
  container.masonry({
      columnWidth:0,
      isOriginLeft: false,
      itemSelector: '.ontime-box',
});
```
Thank you.

**Comment by cloudkite** [comment]
@arifhussain353 sorry you have got the wrong repo, this is the iOS objc project not the jQuery Masonry plugin

**Comment by arifhussain353** [comment]
I'm sorry.It's my misunderstanding.
