### ISSUE TITLE
iOS masonry iOS works OK in iOS7 or Later,but Crash on iOS6

### ISSUE THREAD

**Issue by yizhaorong** [SnapKit/Masonry#279]
@interface OMTMessageCell()

@property (nonatomic, weak) UIImageView *portraitView;

@property (nonatomic, weak) UILabel *contentLabel;

@property (nonatomic, weak) UILabel *sendTimeLabel;

@property (nonatomic, weak) UIImageView *divideLine;

@property (nonatomic, strong) UIView *selectedBackground;

@end

@implementation OMTMessageCell

+ (instancetype)cellWithTableView:(UITableView *)tableView{
    OMTMessageCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    if(!cell){
        cell = [[OMTMessageCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
    }
    [cell setLayout];
    return cell;
}
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    if(self = [super initWithStyle:style reuseIdentifier:reuseIdentifier]){
        [self initSubviews];
        
        self.backgroundColor = [UIColor clearColor];
        self.selectedBackgroundView = self.selectedBackground;
        self.selectionStyle = UITableViewCellSelectionStyleDefault;
        self.backgroundColor = [UIColor clearColor];
    }
    return self;
}

- (UIView *)selectedBackground{
    if(!_selectedBackground){
        _selectedBackground = [[UIView alloc] init];
        _selectedBackground.backgroundColor = ColorWithHexValue(0x501e07, 0.1);
    }
    return _selectedBackground;
}

- (void)initSubviews{
    UIImageView *portraitView = [[UIImageView alloc] init];
    portraitView.contentMode = UIViewContentModeScaleAspectFill;
    portraitView.clipsToBounds = YES;
    portraitView.layer.cornerRadius = OneMT_UserAvatar_Width*0.5;
    portraitView.layer.masksToBounds = YES;
    [self addSubview:portraitView];
    _portraitView = portraitView;
    
    UILabel *contentLabel = [[UILabel alloc] init];
    contentLabel.font = ContentFont;
    contentLabel.textColor = OneMT_PostShow_NameColor;
    contentLabel.numberOfLines = 0;
    [self addSubview:contentLabel];
    _contentLabel = contentLabel;
    
    UILabel *sendTimeLabel = [[UILabel alloc] init];
    sendTimeLabel.font = TimeFont;
    sendTimeLabel.textColor = OneMT_PostShow_Light_TextColor;
    [self addSubview:sendTimeLabel];
    _sendTimeLabel = sendTimeLabel;
    
    UIImageView *divideLine = [[UIImageView alloc] initWithImage:[UIImage imageSDKNamed:@"line_1"]];
    [self addSubview:divideLine];
    _divideLine = divideLine;
}

- (void)setLayout{
    CGFloat portraitWH = OneMT_UserAvatar_Width;
    if([[OMTLocationManager sharedInstance] checkIsArabic]){
        [_portraitView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.mas_equalTo(ContentView).offset(-MessageCellLeftPadding);
            make.width.height.mas_equalTo(portraitWH);
            make.centerY.mas_equalTo(ContentView);
        }];
        
        [_contentLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.mas_equalTo(_portraitView.mas_left).offset(-MessageCellLeftPadding);
            make.left.mas_equalTo(ContentView).offset(MessageCellRightPadding);
            make.centerY.mas_equalTo(_portraitView);
        }];
        
        [_sendTimeLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(_contentLabel);
            make.bottom.mas_equalTo(ContentView).offset(-MessageCellRightPadding);
        }];
        
        _contentLabel.textAlignment = NSTextAlignmentRight;
    }else{
        [_portraitView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(ContentView).offset(MessageCellLeftPadding);
            make.width.height.mas_equalTo(portraitWH);
            make.centerY.mas_equalTo(ContentView);
        }];

        [_contentLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(_portraitView.mas_right).offset(MessageCellLeftPadding);
            make.right.mas_equalTo(ContentView).offset(-MessageCellRightPadding);
            make.centerY.mas_equalTo(_portraitView);
        }];
        
        [_sendTimeLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.mas_equalTo(_contentLabel);
            make.bottom.mas_equalTo(ContentView).offset(-MessageCellRightPadding);
        }];
        _contentLabel.textAlignment = NSTextAlignmentLeft;
    }
    [_divideLine mas_makeConstraints:^(MASConstraintMaker *make) {
        make.bottom.mas_equalTo(-_divideLine.image.size.height);
        make.left.right.mas_equalTo(0);
        make.height.mas_equalTo(_divideLine.image.size.height);
    }];
}

- (void)updateLayout{
    [_sendTimeLabel mas_updateConstraints:^(MASConstraintMaker *make) {
        make.width.mas_equalTo([_sendTimeLabel sizeThatFits:CGSizeMake([UIScreen mainScreen].bounds.size.width, MAXFLOAT)]);
    }];
}

- (void)setMessage:(OMTMessageType *)message{
    _message = message;
    
    [_portraitView sd_setImageWithURL:[NSURL URLWithString:message.senderAvatar] placeholderImage:[UIImage imageNamed:@"loading_default"]];
    _contentLabel.text = message.msgTypeDesc;
    _sendTimeLabel.text = [[NSDate dateWithTimeIntervalSince1970:message.sendTime] timeAgo];
    //更新布局
    [self updateLayout];
}

ERROR Message:
2015-11-23 18:25:43.294 OneMTDemo[1526:907] *** Assertion failure in -[OMTMessageCell layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2380.17/UIView.m:5776
2015-11-23 18:25:43.298 OneMTDemo[1526:907] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. OMTMessageCell's implementation of -layoutSubviews needs to call super.'
*** First throw call stack:
(0x336782a3 0x3b3a097f 0x3367815d 0x33f4dab7 0x354838b3 0x2f49e7 0x3522dd8b 0x3522d929 0x35483689 0x354cbef1 0x3567d1ad 0x354ce0a9 0x354ce05d 0x354cb565 0x354b0313 0x354c77cf 0x35483803 0x3522dd8b 0x3522d929 0x3522e85d 0x3522e243 0x3522e051 0x3522deb1 0x3364d6cd 0x3364b9c1 0x3364bd17 0x335beebd 0x335bed49 0x371972eb 0x354d4301 0xce83d 0x3b7d7b20)
libc++abi.dylib: terminate called throwing an exception
please help me

**Comment by cloudkite** [comment]
@yizhaorong I think you will have better success if you try to use the following conventions https://github.com/SnapKit/Masonry/#where-should-i-create-my-constraints

ie use `[self setNeedsUpdateConstraints];` so that UIkit can decide when the best time to relayout your view is rather trying to force an update

**Comment by yizhaorong** [comment]
@cloudkite Thanks

**Comment by robertjpayne** [comment]
Closing as believe it's resolved, please open a new issue if you encounter further bugs!
