### ISSUE TITLE
When use Masonry to layout tableview.tableHeaderView,in ios 6.0, it will crashed?

### ISSUE THREAD

**Issue by CoderJackyHuang** [SnapKit/Masonry#280]
When use Masonry to layout tableview.tableHeaderView,in ios 6.0, it will crashed.
Can you tell me how to use? When crash, it usually happen in tableview’s method -layoutSublayersOfLayer:

I really don’t know why it can crash in iOS 6.0, but works well in other system.

Do you know what’s the reason? I’m waiting for your reply.

Thank you in advance!

**Comment by cloudkite** [comment]
please provide a stacktrace so we can understand what kinda of exception you are encoutering

**Comment by CoderJackyHuang** [comment]
2014-02-07 10:49:13.041 ErikApp[10597:70b] *** Assertion failure in -[UITableView layoutSublayersOfLayer:], /SourceCache/UIKit_Sim/UIKit-2903.23/UIView.m:8540
2014-02-07 10:49:13.383 ErikApp[10597:70b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. UITableView's implementation of -layoutSubviews needs to call super.'

**Comment by CoderJackyHuang** [comment]
My codes are:

- (void)configTableView {
  self.tableView = [[UITableView alloc] init];
  [self.view addSubview:self.tableView];
  [self.tableView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.edges.mas_equalTo(self.view);
  }];
  
  UIView *headerView = [[UIView alloc] initWithFrame:self.view.bounds];
  self.tableView.tableHeaderView = headerView;
  
  UIImageView *imgView = [[UIImageView alloc] init];
  [headerView addSubview:imgView];
  imgView.backgroundColor = [UIColor greenColor];
  imgView.layer.cornerRadius = 50;
  imgView.layer.masksToBounds = YES;
  imgView.layer.borderWidth = 0.5;
  imgView.layer.borderColor = [UIColor redColor].CGColor;
  
  CGFloat screenWidth = [UIScreen mainScreen].bounds.size.width;
  
  UILabel *tipLabel = [[UILabel alloc] init];
  tipLabel.text = @"这里是提示信息，通常会比较长，可能会超过两行。为了适配6.0，我们需要指定preferredMaxLayoutWidth，但是要注意，此属性一旦设置，不是只在6.0上生效，任意版本的系统的都有作用，因此此值设置得一定要准备，否则计算结果会不正确。我们一定要注意，不能给tableview的tableHeaderView和tableFooterView添加约束，在6.0及其以下版本上会crash，其它版本没有";
  tipLabel.textAlignment = NSTextAlignmentCenter;
  tipLabel.textColor = [UIColor blackColor];
  tipLabel.backgroundColor = [UIColor clearColor];
  tipLabel.numberOfLines = 0;
  tipLabel.preferredMaxLayoutWidth = screenWidth - 30;
  [headerView addSubview:tipLabel];
  
  UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
  [button setTitle:@"Show detail" forState:UIControlStateNormal];
  [button setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
  [button setBackgroundColor:[UIColor blueColor]];
  button.layer.cornerRadius = 6;
  button.clipsToBounds = YES;
  button.layer.masksToBounds = YES;
  
  [headerView addSubview:button];
  
  [headerView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.top.mas_equalTo(0);
    make.width.mas_equalTo(self.view);
    make.bottom.mas_equalTo(button.mas_bottom).offset(60).priorityLow();
    make.height.greaterThanOrEqualTo(self.view);
  }];
  
  [imgView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.mas_equalTo(80);
    make.centerX.mas_equalTo(headerView);
    make.width.height.mas_equalTo(100);
  }];
  
  [tipLabel mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.mas_equalTo(15);
    make.right.mas_equalTo(-15);
    make.top.mas_equalTo(imgView.mas_bottom).offset(40);
  }];
  [button mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.mas_greaterThanOrEqualTo(tipLabel.mas_bottom).offset(80);
    make.left.mas_equalTo(15);
    make.right.mas_equalTo(-15);
    make.height.mas_equalTo(45);
  }];
}


and only crash in ios 6.0:

2015-12-03 15:12:46.249 learnMasonry[9858:907] *** Assertion failure in -[UITableView layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2380.17/UIView.m:5776
2015-12-03 15:12:46.251 learnMasonry[9858:907] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. UITableView's implementation of -layoutSubviews needs to call super.'
*** First throw call stack:
(0x313e22a3 0x390ff97f 0x313e215d 0x31cb7ab7 0x331ed8b3 0x32f97d8b 0x32f97929 0x32f9885d 0x32f98243 0x32f98051 0x32f97eb1 0x313b76cd 0x313b59c1 0x313b5d17 0x31328ebd 0x31328d49 0x34eff2eb 0x3323e301 0x9c69d 0x39536b20)
libc++abi.dylib: terminate called throwing an exception

**Comment by robertjpayne** [comment]
@CoderJackyHuang you're sort of out of luck here, until iOS 8 using constraints with table header views has been extremely finicky. It's even still a bit troublesome on iOS 8. I recommend using manual layouts for table header views.

**Comment by crazytom26** [comment]
I got this problem when I added a no data View on the tableview,and run the project on iOS7,

`*** Assertion failure in -[UITableView layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2935.138/UIView.m:8794
2016-07-29 13:39:02.187 WanXueEDU[458:60b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. UITableView's implementation of -layoutSubviews needs to call super.'`
