### ISSUE TITLE
Add origin and frame constraints

### ISSUE THREAD

**Issue by michaeleiselsc** [SnapKit/Masonry#282]
Something like this:
```
[view mas_makeConstraints:^(MASConstraintMaker *make) {
    make.frame.mas_equalTo(frame);
}];
```
and
```
[view mas_makeConstraints:^(MASConstraintMaker *make) {
    make.origin.mas_equalTo(origin);
}];
```

These would be very helpful methods in certain situations!

**Comment by cloudkite** [comment]
@michaeleiselsc Thanks for the suggestion. My reservation is that Autolayout and CGRect based layout are fundamentally quite different and do not mix well. I think it would be error prone and confusing to try mixed both concepts.

**Comment by michaeleiselsc** [comment]
@cloudkite sure, but there are use cases where all we have is a CGRect, and so we need some way of using that. the only downside i see is that some people might use it when it's unnecessary, e.g. `make.frame.mas_equalTo(superview.bounds)`

**Comment by cloudkite** [comment]
Its not as concise but you can use

```
make.size.mas_equalTo(frame.size);
make.left.mas_equalTo(CGRectGetMinX(frame));
make.top.mas_equalTo(CGRectGetMinY(frame));
```

**Comment by michaeleiselsc** [comment]
yeah that's the alternative

**Comment by michaeleiselsc** [comment]
btw, have you ever actually run into a case in practice where the rect had a negative height or width, and so CGRectGetMinX was necessary?

**Comment by robertjpayne** [comment]
@michaeleiselsc going to agree with @cloudkite that mixing the concepts is just going to cause a headache of mixed concepts.

Personally never used negative rects on iOS but have on OS X.
