### ISSUE TITLE
TVOS Support

### ISSUE THREAD

**Issue by mariohahn** [SnapKit/Masonry#285]
Is it possible to add TVOS Support? would be awesome (: 

thx.

**Comment by cloudkite** [comment]
Hi @mariohahn I think the main blocker would be https://github.com/SnapKit/Masonry/blob/master/Masonry/MASUtilities.h#L11
which I think needs to be something like `#if TARGET_OS_IPHONE || TARGET_OS_TV`

If you want to try you can basically grab everything in https://github.com/SnapKit/Masonry/tree/master/Masonry

include it directly in your project and edit that line in `MASUtilities` and see how it goes from there.
If you do have any luck would welcome a PR :)

**Comment by cloudkite** [comment]
In addition for backwards compatibility would be good to check if TARGET_OS_TV is defined

```
#ifndef TARGET_OS_TV
  #define TARGET_OS_TV 0
#endif
```

**Comment by mariohahn** [comment]
https://github.com/SnapKit/Masonry/pull/286

**Comment by robertjpayne** [comment]
Now available on Cocoapdos
