### ISSUE TITLE
How to constraints flowLayout of collectionView with Masonry

### ISSUE THREAD

**Issue by synemin** [SnapKit/Masonry#288]
I want use the Masonry to constraint flowLayout, but it doesn't work. 
Even i can't use the block of make 
THANKS

**Comment by robertjpayne** [comment]
Please include more accurate description of your issue/feature and sample code as you can. Unfortunately we cannot do much but close issues of this nature.

**Comment by synemin** [comment]
SYBaseCollectionViewFlowLayout *flowLayout = [[SYBaseCollectionViewFlowLayout alloc] initWithItemSize:CGSizeMake(100, 100) scrollDirection:UICollectionViewScrollDirectionHorizontal sectionInsert:UIEdgeInsetsMake(1, 3, 1, 3)];
    
    self.collection = [[SYBaseCollectionView alloc] initWithFrame:self.view.frame collectionViewLayout:flowLayout backgroundColor:[UIColor whiteColor] superView:self.backOfSCView showsHorizontalScrollIndicator:NO showsVerticalScrollIndicator:NO delegate:self];
    
    [self.collection makeConstraints:^(MASConstraintMaker *make) {
        make.left.bottom.and.right.equalTo(self.backOfSCView);
        HEIGHTToNum(120);
    }];
There is a mistake that negative or zero item sizes are not supported in the flow layout, when i use masonry. There other one is that i need A collectionView on B collectionView, when i Landscape it does't work, and will deranged.
