### ISSUE TITLE
cannot run 'pod install'

### ISSUE THREAD

**Issue by Ethandf90** [SnapKit/Masonry#289]
Fetching podspec for `Masonry` from `./`
[!] Unable to satisfy the following requirements:

- `Masonry (from `./`)` required by `Podfile`
- `Masonry (from `./`)` required by `Podfile`
- `Masonry (= 0.6.1)` required by `Podfile.lock`

**Comment by robertjpayne** [comment]
Can you post up your full Podfile? And have you tried updating Cocoapods?

**Comment by robertjpayne** [comment]
Closing for now due to inactivity, please re-open if you have further info to provide.
