### ISSUE TITLE
Animation can not work on ios7

### ISSUE THREAD

**Issue by wszcug** [SnapKit/Masonry#290]
I find a bug in a project which uses masonry on ios7, the animation can not work,
for example,when i create a view,and make it frame change use aniamation. on ios8 or later,it works well,but the same code ,it can not work on ios7, the aniamtion shuold be a transition，but i find it instantaneously complete.

**Comment by wszcug** [comment]
hi can somebody answer my question ? thanks!

**Comment by robertjpayne** [comment]
@wszcug best if you post some sample code.

**Comment by wszcug** [comment]
@robertjpayne maybe i made a mistake , thanks for you anwer,i'll check my code and timely feedback

**Comment by robertjpayne** [comment]
@wszcug ok, re-open with some sample code if you feel you need more assistance
