### ISSUE TITLE
Assertion failure in -[Rview layoutSublayersOfLayer:],

### ISSUE THREAD

**Issue by app111** [SnapKit/Masonry#291]
*** Assertion failure in -[Rview layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2935.138/UIView.m:8794

-(void)layoutSubviews
{
  [super layoutSubviews];
  [self.backgroundImageView mas_remakeConstraints:^(MASConstraintMaker *make) {
    make.edges.equalTo(self).with.insets(UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, 0.0f));
  }];
}

**Comment by lianchengjiang** [comment]
put [super layoutSubviews]; to the end of -(void)layoutSubviews。

**Comment by lianchengjiang** [comment]
because autolayout calculate frame at  [super layoutSubviews];。you should not add constraint after [super layoutSubviews] , which layout is finished

**Comment by lianchengjiang** [comment]
and i think remarkConstraint in - (void)updateConstraints is more suitable。https://github.com/SnapKit/Masonry/#where-should-i-create-my-constraints

**Comment by robertjpayne** [comment]
@lianchengjiang you don't want to make constraints during a layout pass as it will cause a recursive layout ( hence why you get the crash since UIKit detects this and realises it's going to go into a recursive layout ).

Try to setup your constraints in `updateConstraints` method or an initializer.
