### ISSUE TITLE
multipliedBy(0.33) is ok. but multipliedBy(1/3) is not.

### ISSUE THREAD

**Issue by luna-moonfang** [SnapKit/Masonry#296]
Is that a bug? Or there's a work-around?

**Comment by xingheng** [comment]
NO.

The expression 1 / 3 equals to 0 (int), 1.0f / 3.0f equals to 0.3333 (float)....
It depends on you.

I prefer to use dividedBy(3).

**Comment by luna-moonfang** [comment]
Thank you @xingheng . That helps a lot.
