### ISSUE TITLE
How do I change the multiplier?

### ISSUE THREAD

**Issue by AveryLiu** [SnapKit/Masonry#297]
I'm not sure if I overlooked something, but I didn't find the guide on changing the multiplier.  

Say I have a view and I want to make it half of its superview's height. We can utilize Masonry as following:
`make.top.equalTo(superview.mas_top);`
`make.left.equalTo(superview.mas_left); `
`make.height.equalTo(superview.mas_height)  // Here it should be half of its superview's height, but how?`
`make.right.equalTo(superview.mas_right);`

**Comment by robertjpayne** [comment]
@AveryLiu you can do `equalTo(other).multipliedBy(0.5)` however, you cannot alter the multiplier ( NSLayoutConstraint does not allow it ) so you need to use `mas_remakeConstraints` to update it.
