### ISSUE TITLE
make.size.height does not action same as make.height

### ISSUE THREAD

**Issue by imrazor** [SnapKit/Masonry#298]
Hi, thanks for such a good auto layout library

I find that:

[_topLine mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(_cardTitleLabel);
        make.height.mas_equalTo(kLineHeight);
//make.size.height.mas_equalTo(kLineHeight);//if yo type this code, your _topLine will not get stretching
}];

I don't know if this is a bug, but it's confuse me a lot when I use "make.size.height" 

Thank you!

**Comment by robertjpayne** [comment]
@imrazor API usage speaking should only work with `make.height` not `make.size.height`. Unfortunately we can't do much to prevent improper API usage in Objective-C like this. Thanks for the heads up though!
