### ISSUE TITLE
mas_equalTo issue

### ISSUE THREAD

**Issue by JxbSir** [SnapKit/Masonry#303]
I want to use “mas_equalTo”  with height of "35.7".

But the control's real height is "35.5" after making constraint.  WHY?

How can i solve this issue?

**Comment by nickynick** [comment]
Auto Layout rounds values to closest pixel (your device screen is likely 2x, so the pixel is 0.5). It makes perfect sense because it assures that your views won't have blurry edges. Is there a reason why you'd want the height to be 35.7 exactly?

**Comment by JxbSir** [comment]
I have a label which maybe has many lines.
And i calculate the height before it will be displayed, then the height is 35.7.
If the height will be rounded to 35.5,  the last line of this label's text can't be displayed.

**Comment by nickynick** [comment]
This is usually solved by ceiling the value you get from text size calculation - as far as I remember, `UILabel` internally does the same thing to calculate its own size.

**Comment by JxbSir** [comment]
Yeah, ceiling can solve this problem, but i can't understand why Auto Layout did not round to 36.0

**Comment by nickynick** [comment]
That's because it rounds the value to the closest actual pixel. So the values it chooses from are 35.0, 35.5 and 36.0 - and 35.7 is closer to 35.5 than 36.0 :)

**Comment by JxbSir** [comment]
I already tried it,   35.95 also will be rounded to 35.5

**Comment by nickynick** [comment]
That's strange. I'd guess they use floor to round the value, but apparently this is not the case too, judging by [this answer](http://stackoverflow.com/a/16285106/971055). Well, anyway, you should be safe with ceiling.

**Comment by JxbSir** [comment]
Thank you very much.
