### ISSUE TITLE
update height did not work ？

### ISSUE THREAD

**Issue by JxbSir** [SnapKit/Masonry#304]
The height of a label is 122，when new height is 71，and i update this height to 71，then i call “layoutIfNeeded” .   But this height still is 122.

please see the picture.

![2 pic](https://cloud.githubusercontent.com/assets/9983806/12709808/7c974606-c8ea-11e5-9026-29ba0d3cecda.jpg)

**Comment by Jatstar** [comment]
试一试`self.lblContent.superview.layoutIfNeeded `

**Comment by JxbSir** [comment]
when use "setNeedsLayout"， it can work

**Comment by bigParis** [comment]
setNeedsLayout don't work either

**Comment by robertjpayne** [comment]
I notice this is a `mas_updateConstraints` what else do you by chance have creating constraints on this label or is this the only constraint?

**Comment by bigParis** [comment]
@robertjpayne I make my constraints in my xib file,  and I update it by using mas_updateConstraints, It is still the height made in xib,but if I don't make it ,all the subviews in my view will not gain the frame, There is a lot of subviews, I don't want to make their constraints by coding, Must I make their constraints by coding?I just want  my superview' height can change height with the subview's height

**Comment by robertjpayne** [comment]
@bigParis 

Ok last thing to try:

`[self setNeedsLayout]` and then `[self layoutIfNeeded]` you probably need both of these in combo. Also you don't have any log messages about constraint conflicts do you?

**Comment by bigParis** [comment]
I use
 [self setNeedsLayout] and then [self layoutIfNeeded] and
I got this log below	
Probably at least one of the constraints in the following list is one you don't want. 
(1) look at each constraint and try to figure out which you don't expect; 
(2) find the code that added the unwanted constraint or constraints and fix it. 

    [self.tagCollectionView mas_updateConstraints:^(MASConstraintMaker *make) {
        make.height.equalTo(@(collectionViewHeight));
    }];
this is my updateConstraints in my .m file, and in my xib I make 4 constraints(left, top, width, height)
Should I my 4 constraints all by mas_makeConstraints?

**Comment by bigParis** [comment]
@robertjpayne 
I use
[self setNeedsLayout] and then [self layoutIfNeeded] and
I got this log below

Probably at least one of the constraints in the following list is one you don't want. 
(1) look at each constraint and try to figure out which you don't expect; 
(2) find the code that added the unwanted constraint or constraints and fix it.

[self.tagCollectionView mas_updateConstraints:^(MASConstraintMaker *make) {
    make.height.equalTo(@(collectionViewHeight));
}];
this is my updateConstraints in my .m file, and in my xib I make 4 constraints(left, top, width, height)
Should I my 4 constraints all by mas_makeConstraints?

**Comment by robertjpayne** [comment]
@bigParis yea you may try to make them all in code, or you need to ensure the IB ones that will conflict are set to "placeholder" so they are removed at runtime.

**Comment by bigParis** [comment]
@robertjpayne Thanks for your advice, it works well when I make them all in code, but there are still some puzzling thing
1 look at this code 
    [self.animationView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left).offset(15);
        make.centerX.equalTo(self.mas_centerX);
        make.height.equalTo(@(265));
        make.centerY.equalTo(self.mas_centerY);
    }];
//    [self setNeedsLayout];
    [self.animationView layoutIfNeeded];
    
    [self.mainView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.animationView.mas_left);
        make.centerX.equalTo(self.animationView.mas_centerX);
        make.height.equalTo(@(184));
        make.centerY.equalTo(self.mas_centerY);
    }];

mainView is a subview of animationView, I want it transform with animationView, but the code make by using this way is not work, but I set a breakpoint an line [self.mainView...], I see the frame is right fit with the screen, but mainView isn't.

2 when I use  [self.animationView layoutIfNeeded]; the frame of animationView will change,but when I need to use setNeedsLayout?

**Comment by robertjpayne** [comment]
@bigParis using `setNeedsLayout` will ensure that `layoutIfNeeded` works. `layoutIfNeeded` only performs a layout pass if the view, or anything in it's subviews tree is flagged as `setNeedsLayout`.

Masonry installs constraints on the 'closest common superview' based on the constraints you're making. This is a requirement by UIKit that the NSLayoutConstraints we create are installed on the superview or higher up the view chain. 

Because of this weird superview logic you may find you need to call `setNeedsLayout` or `layoutIfNeeded` on a superview or even a few superviews up.

Based on your code you want to call it on `animationView.superview` or `mainView.superview` whichever is a greater ancestor.

**Comment by bigParis** [comment]
@robertjpayne Perhaps I know what is the different. The views in ReadMe and Masonry's example code is created by code, but in my project, I load the views from nib.
If I make constraints in awakeFromNib, it doesn't work,the code is 
- (void)awakeFromNib {
   [super awakeFromNib];
    self.frame = CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
    
    [self.animationView makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left).offset(15);//make.left.equalTo([self.animationView.superview.mas_left).offset(15); doesn't work either
        make.centerX.equalTo(self.mas_centerX);
        make.height.equalTo(@(265));
        make.centerY.equalTo(self.mas_centerY);
    }];
//    [self setNeedsLayout];
    [self.animationView layoutIfNeeded];

 if I get the view from nib and add it to self, the right superview of animationView is self.subvies[0](the self has only one child), it doesn't work when I code in this way:


- (instancetype)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {
        UIView *view = [[[NSBundle mainBundle] loadNibNamed:@"MFChatRoomFilterView"
                                                      owner:self
                                                    options:nil]
                        firstObject];
        view.frame = frame;
        self.frame = frame;
        [self addSubview:view];
        [self initViews];
    }
    return self;
}
- (void) initViews {
    UIView *superview = self.subviews[0];
    [self.animationView makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(superview.mas_left).offset(15);
        make.centerX.equalTo(superview.mas_centerX);
        make.height.equalTo(@(265));
        make.centerY.equalTo(superview.mas_centerY);
    }];
//    [self setNeedsLayout];
    [self.animationView layoutIfNeeded];
}


So, it seems that masonry cannot work well with xib, isn't it?

**Comment by robertjpayne** [comment]
@bigParis yea Masonry doesn't work well with Xibs, you need to ensure the constraints that may conflict that are created in the Xibs are set to "Placeholder" and re-create them with Masonry or only add additional constraints that wont cause conflicts.

**Comment by ChenReason** [comment]
My opinion is that the reason of this kind of problems is the view would be added some system constraints like NSContentSizeLayoutConstraint, and then when you add SnapKit's or Masorny's constraints in the same view, it leads to constraint conflicts.
