### ISSUE TITLE
Where do you specify NSLayoutFormatDirectionRightToLeft options

### ISSUE THREAD

**Issue by reejosamuel** [SnapKit/Masonry#305]
Working on multi language app that supports right to left languages such as arabic. Using the `NSLayoutFormatOptions` option such `NSLayoutFormatDirectionRightToLeft` is very critical.

Wondering where do you specify these option, could find it anywhere in the docs.

Thanks

**Comment by robertjpayne** [comment]
@reejosamuel as far as I'm aware these are automatically set by iOS and you are to use them to configure your layout?

We don't support configuring this, it's recommending to use leading and trailing constraints rather than left/right if you need to support right to left languages.

**Comment by reejosamuel** [comment]
They can be set when using VFL, this holds the key to switching language without restarting the app.

**Comment by robertjpayne** [comment]
@reejosamuel I think the reason it can be set for VFL is because for VFL you're not really specifying leading vs trailing or left vs right.

As far as Masonry is concerned left is always visually left and right is always visually right. You want to use leading/trailing rather than left/right when you want to support RTL languages and you shouldn't need to configure anything else.

**Comment by reejosamuel** [comment]
Ok well thanks, trailing and leading works for when the language change is done after a force crash or asking the user to restart the app. In our case we let the user change language on the fly and for this, specifying this option is essential. 

I had a look into masonry to figure out if I could send a pull request but since you don't use VFL obviously and it's not posible to specify this option using any other apple's auto layout API. At least as far as I know, we can close this issue for now. Maybe a future release could have it if apple changes their weird ways.

**Comment by robertjpayne** [comment]
@reejosamuel Yea sorry there's not much we can do about it there, using VFL from the Constraint DSL isn't very suitable.

You can read the current interface layout direction ( which I believe changes w/o restarting app ) and adjust your constraint setup accordingly.
