### ISSUE TITLE
Constraint install and activate

### ISSUE THREAD

**Issue by xserver** [SnapKit/Masonry#307]
Can you provide an example of install and activate?

#### MASConstraint
```objective-c
- (void)activate { MASMethodNotImplemented(); }
- (void)deactivate { MASMethodNotImplemented(); }
- (void)install { MASMethodNotImplemented(); }
- (void)uninstall { MASMethodNotImplemented(); }
```

**Comment by evilDave** [comment]
I second this please.
I was trying to add two constraints that would be conflicting (two different height constraints) then activate/deactivate or install/uninstall them but neither works, it produces a conflict. I ended up having to remove and re-add all constraints.
Some nicer way to add an inactive constraint would be nice too.

**Comment by xserver** [comment]
@evilDave 
uninstall constraint, system will be release it.
so, you need use strong reference the constraint.

**Comment by robertjpayne** [comment]
You need to capture a strong reference to a constraint in the make/remake block:

```
self.constraint = make.left.equalTo(50);
```

You can then do

```
[self.constraint uninstall];
```

If this doesn't solve your issue please re-open a new issue with a sample project.
