### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Cannot modify constraints for UINavigationBar managed by a controller'

### ISSUE THREAD

**Issue by evilDave** [SnapKit/Masonry#309]
I have a UINavigationController subclass that adds some views to the self.navigationBar, those views then get positioned relative to the navigationBar.

I am in the process of converting from NSLayoutAnchor to Masonry (to better support iOS8) and have found an issue with one modification, from this:

```
[logoImageView.centerXAnchor constraintEqualToAnchor:self.navigationBar.centerXAnchor].active = YES;
```

to (what if think it should be) this:

```
[logoImageView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.centerX.equalTo(self.navigationBar.mas_centerX);
}];
```

This produces this error:

`
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot modify constraints for UINavigationBar managed by a controller'
`

The original code is able to add the constraint to the navigationBar but not the masonry code.

**Comment by robertjpayne** [comment]
@evilDave interesting, probably some internal hijinks that only works with anchors, does it work if you use the standard NSLayoutConstraint API?

**Comment by evilDave** [comment]
It does.
```
[NSLayoutConstraint constraintWithItem:logoImageView attribute:NSLayoutAttributeCenterX relatedBy:NSLayoutRelationEqual toItem:self.navigationBar attribute:NSLayoutAttributeCenterX multiplier:1 constant:0].active = YES;
```

**Comment by robertjpayne** [comment]
@evilDave interesting! It must be that where we attempt to install it is invalid compared to the `activate` command which lets UIKit decide.

**Comment by robertjpayne** [comment]
@evilDave I think the issue is that the newer `activate/deactivate` api's find the right place to install the constraints but we cannot ( it's probably a private API )

In the `master` branch all constraints by default are now using the activate/deactivate methods rather than our custom algorithm so this should work now.

I will advise though if the activate/deactivate methods are not available it will cause a crash still!
