### ISSUE TITLE
iOS 6 uitableviewcell crash 

### ISSUE THREAD

**Issue by coderyi** [SnapKit/Masonry#310]
iOS 6 uitableviewcell crash ,i add "mas_makeConstraints" in "initWithStyle"

and crash log :

Auto Layout still required after executing -layoutSubviews. DESettingTableViewCell's implementation of -layoutSubviews needs to call super.

**Comment by robertjpayne** [comment]
@coderyi sounds like someone isn't calling `[super layoutSubviews]` inside that cell. Can you check? Either way this is likely unrelated to Masonry.
