### ISSUE TITLE
close Wiki, if not in use.

### ISSUE THREAD

**Issue by luckytianyiyan** [SnapKit/Masonry#311]
It has been implanted in advertising.
@youran1024 
![image](https://cloud.githubusercontent.com/assets/7489176/13452397/4c50e11e-e082-11e5-92da-09884ae95130.png)

![image](https://cloud.githubusercontent.com/assets/7489176/13452364/11597c7e-e082-11e5-897a-a0ee2b531528.png)

**Comment by cloudkite** [comment]
@luckytianyiyan Thanks for reporting :+1:
