### ISSUE TITLE
addConstraint/removeConstraint are deprecated

### ISSUE THREAD

**Issue by Subloran** [SnapKit/Masonry#312]
Hello,

LayoutConstraint methods of UIView are deprecated in iOS 9. New class methods are added to NSLayoutConstraint.
Could you please add iOS 9 layout methods supporting? The new way is using [NSLayoutConstraint activateConstraints:] instead of [view addConstraints].
I'm using checks for system version to use this functions.

**Comment by robertjpayne** [comment]
@Subloran this is now live in master, will probably do a release in a bit.
