### ISSUE TITLE
self.navigationController.view addSubView result in that backIndicatorView move up

### ISSUE THREAD

**Issue by zhigangfang** [SnapKit/Masonry#315]
![screen shot 2016-03-14 at 10 30 01 pm](https://cloud.githubusercontent.com/assets/3981274/13747688/6c39bdbe-ea34-11e5-9a2f-6de5a8060e11.png)
Anybody can help me?

**Comment by robertjpayne** [comment]
@zhigangfang you'll need to manually inset it from the top… `make.top.equalTo(view).offset(@20)` or something similar.
