### ISSUE TITLE
Example can't run  

### ISSUE THREAD

**Issue by yhdevelop** [SnapKit/Masonry#316]
Masonry/Pods/Target Support Files/Pods-Masonry iOS Examples-Masonry/Pods-Masonry iOS Examples-Masonry-prefix.pch' file not found 

I don't know why

**Comment by GloriousOnion** [comment]
You need install cocoapods first, then go the directory and run "pod install".

**Comment by robertjpayne** [comment]
@yhdevelop this is now fixed on master
