### ISSUE TITLE
[Question] "Easier way" to utilise Masonry with UILabel

### ISSUE THREAD

**Issue by sao101** [SnapKit/Masonry#317]
As per [MASExampleLabelView.m](https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleLabelView.m) on Nov 26, 2013

> "// for multiline UILabel's you need set the preferredMaxLayoutWidth
>     // you need to do this after [super layoutSubviews] as the frames will have a value from Auto Layout at this point
> 
>     // stay tuned for new easier way todo this coming soon to Masonry"

Has a "new easier way todo this" been implemented?

**Comment by robertjpayne** [comment]
@sao101 unfortunately we should probably remove that, there isn't an easier way at this time.
