### ISSUE TITLE
mas_makeConstraints not working in the iPad version

### ISSUE THREAD

**Issue by soufianeEssabbane** [SnapKit/Masonry#318]
Hi thank you for the awesome work you're doing. I have an universal app and i'm using mas_makeConstraints to create kind of padding between cells like :
 `    UIEdgeInsets padding = UIEdgeInsetsMake(5, 10, 5, 10);

    [self.contentView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self).with.insets(padding);
    }];` 
it works fine in all iPhones, but not in the iPad version ? am i missing something ? any help is appreciated, thanks.

**Comment by jlevinAP** [comment]
The code comments for equalTo state that it accepts a MASViewAttribute, UIView, NSValue, or NSArray.  So check the type of 'self' to make sure it can be used.

Typically, I'll do `equalTo(self.view)`

**Comment by soufianeEssabbane** [comment]
hi @jlevinAP  thanks  for the reply, the self is a cell view and as i said it works fine in all iPhones and also in iPad 9.1 simulateur ... but not in real device ... I use it to create a kind of padding between cells.

**Comment by robertjpayne** [comment]
@soufianeEssabbane is this inside a Form Sheet modal view controller by chance?

**Comment by soufianeEssabbane** [comment]
@robertjpayne no is a cellview in a tableview in a viewcontroller. 
in another issue i have read that labels may break the constraints but I didn't understand why ...

**Comment by jlevinAP** [comment]
Is there any output in the console?  Maybe an autoresizing mask is creating conflicting constraints.

**Comment by soufianeEssabbane** [comment]
the problem is that when in simulateur it doesn't seems to be a problem but one in device (iPad) it doesn't work and as i said before it works fine in iPhone devices. i'll try to see if there's any output in console related to this issue.
@jlevinAP can you please explain how an autoresizing mask can creat a conflicting constraints ? thanks

**Comment by jlevinAP** [comment]
Yeah if the Autolayout engine can't complete frame calculations for your subviews then it will create autoresizing masks to allow it generate a valid layout.  Sometimes these autoresizing masks can conflict with your manually created constraints and the engine could decide to keep yours or remove them.  If you know you have constraints to satisfy all your subviews positions and size, you can disable this behavior by calling on a UIView setTranslatesAutoresizingMaskIntoConstraints:NO.

**Comment by soufianeEssabbane** [comment]
Thanks @jlevinAP i'll check this too and try

**Comment by soufianeEssabbane** [comment]
@jlevinAP is there any logic difference between iPad and iPhone Autolayout engine ?

**Comment by robertjpayne** [comment]
@soufianeEssabbane I'd just check your layoutMargins just to be sure, I know the iPad gets different layout margins than iPhone.

**Comment by robertjpayne** [comment]
Closing this as I don't believe it's related to Masonry as we've not heard anything similar in a long time. If you can provide a sample project replicating it please feel free to re-open or open a new issue.
