### ISSUE TITLE
README.md  seems to have an error?

### ISSUE THREAD

**Issue by leavesster** [SnapKit/Masonry#323]
> - (void)**updateConstraints** {
>     [self.growingButton mas_updateConstraints:^(MASConstraintMaker *make) {
>         make.center.equalTo(self);
>         make.width.equalTo(@(self.buttonSize.width)).priorityLow();
>         make.height.equalTo(@(self.buttonSize.height)).priorityLow();
>         make.width.lessThanOrEqualTo(self);
>         make.height.lessThanOrEqualTo(self);
>     }];
> 
>     //according to apple super should be called at end of method
>     [super update**View**Constraints];
> }

The end of method called [super **updateViewConstraints**] which should be called in ViewController, not [**updateConstraints**] which should be called in View.
It confuse me. >_<. I think it should be both **updateConstraints** or **updateViewConstraints**

**Comment by robertjpayne** [comment]
@leavesster you're correct! Thanks I've updated this now too.
