### ISSUE TITLE
how do i Set the circular

### ISSUE THREAD

**Issue by wheretakenlu** [SnapKit/Masonry#326]
UIImageView *imageview = [[UIImageView alloc]init];
    [view addSubview:imageview];
    [imageview mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(view);
        make.top.bottom.insets(UIEdgeInsetsMake(10, 0, 10, 0));
        make.width.equalTo(imageview.height);
    }];
    imageview.layer.cornerRadius = imageview.frame.size.height/2;
    imageview.layer.masksToBounds = YES;

i want the imageView to circular ,but it doesnt work，how to do it

**Comment by robertjpayne** [comment]
@wheretakenlu you need to set your cornerRadius in a `layoutSubviews` override as you wont have proper sizing until the layout pass is finished.
