### ISSUE TITLE
How to convert MASConstraint to NSLayoutConstraint?

### ISSUE THREAD

**Issue by RobertNNms** [SnapKit/Masonry#329]
Hi,

How to convert MASConstraint to NSLayoutConstraint?

I would like use JHChainableAnimations:
self.topConstraint = [NSLayoutConstraint ...];
myView.makeConstraint(self.topConstraint, 50).animate(1.0);

Thanks

**Comment by robertjpayne** [comment]
@RobertNNms we don't really support this, a MASConstraint can represent several layout constraints and its not advisable to mess with the underlying NSLayoutConstraints.

What are you trying to accomplish?

**Comment by RobertNNms** [comment]
I would like use "JHChainableAnimations" (https://github.com/jhurray/JHChainableAnimations) rather than "UIView animateWithDuration" with Mansory, for animation resize.
