### ISSUE TITLE
NSLayoutAttributeFirstBaseline support?

### ISSUE THREAD

**Issue by andrewcl** [SnapKit/Masonry#331]
Do you intend on updating Masonry/SnapKit to support NSLayoutAttributeFirstBaseline and NSLayoutAttributeLastBaseline? MASAttributeBaseline works for aligning against a bottom baseline but not a first baseline. Having MASConstraints for first and last baselines would make working with multi line UILabels much easier.

Also, this library is awesome. AutoLayout at times is far too verbose and the DSL you provide makes layout constraints much easier to work with. Thank you so much for creating and maintaining this library.

**Comment by robertjpayne** [comment]
@andrewcl I've added these to Master branch if you can pin Cocoapods to there and give it a test would be appreciated! Will probably release to trunk in a few days.

**Comment by andrewcl** [comment]
@robertjpayne Gave the new mas_firstBaseline & mas_lastBaseline a test and they both work! Would you mind releasing and tagging the updates so that Cocoapods and Carthage can pick this up?
