### ISSUE TITLE
Changelog File Outdated

### ISSUE THREAD

**Issue by aamctustwo** [SnapKit/Masonry#332]
The `Changelog.md` file hasn't been updated since version 0.63. Can we get an updated changelog file that includes the 1.0 changes?

**Comment by robertjpayne** [comment]
@aamctustwo yea we should update this! Not much changed with 1.0 just a few small internal tweaks and the API has been so stable I decided it was ok to jump to 1.0

**Comment by robertjpayne** [comment]
This has been resolved
