### ISSUE TITLE
 iOS7  Specs satisfying the `SnapKit` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by JZJJZJ** [SnapKit/Masonry#333]
how to resolve it

**Comment by liuxu0718** [comment]
require add target.

for example 

platform :ios , '7.0' 
 
pod 'JSONKit', '~> 1.5pre'

add '7.0' can resolve it.

**Comment by JZJJZJ** [comment]
platform :ios, "7.0"
pod 'Masonry'
pod 'SnapKit'
use_frameworks!

it does not work

**Comment by robertjpayne** [comment]
@JZJJZJ SnapKit requires iOS 8.0 or above as dynamic frameworks do not work in iOS 7.0. Please see the SnapKit documentation about using legacy platforms as it does support iOS 7 through manual integration.

There is nothing we can do to resolve this as Cocoapods does not support Swift in iOS 7.0 targets.
