### ISSUE TITLE
When mas_updateConstraints show some errors

### ISSUE THREAD

**Issue by XiangNanLi** [SnapKit/Masonry#337]
I create a view ,centerX is a label's centerX.   when I tap it ,it will change the centerX.
But when I use the mas_updateConstraints ,log shows"
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x140a11070 UILabel:0x140a0e090.centerX == SpaceOrderHeaderView:0x140a0ceb0.centerX - 93>",
    "<MASLayoutConstraint:0x140a11370 UILabel:0x140a0f280.centerX == SpaceOrderHeaderView:0x140a0ceb0.centerX + 94>",
    "<MASLayoutConstraint:0x140a11aa0 UIView:0x140a10240.centerX == UILabel:0x140a0e090.centerX>",
    "<MASLayoutConstraint:0x1409e6fb0 UIView:0x140a10240.centerX == UILabel:0x140a0f280.centerX>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x140a11370 UILabel:0x140a0f280.centerX == SpaceOrderHeaderView:0x140a0ceb0.centerX + 94>
"
and the position of the label changed,but the view not change the position.

**Comment by XiangNanLi** [comment]
Sorry,  I donot know why the log not display. here is the log message.

> Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it
\<MASLayoutConstraint:0x15ed42920 UILabel:0x15ed89740.centerX == SpaceOrderHeaderView:0x15ed99350.centerX - 93>,
    \<MASLayoutConstraint:0x15ed29520 UILabel:0x15d5fbb10.centerX == SpaceOrderHeaderView:0x15ed99350.centerX + 94>,
    \<MASLayoutConstraint:0x15d530b80 UIView:0x15e9b4500.centerX == UILabel:0x15ed89740.centerX>,
    \<MASLayoutConstraint:0x15d7486a0 UIView:0x15e9b4500.centerX == UILabel:0x15d5fbb10.centerX>

> Will attempt to recover by breaking constraint 
\<MASLayoutConstraint:0x15ed29520 UILabel:0x15d5fbb10.centerX == SpaceOrderHeaderView:0x15ed99350.centerX + 94>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.

**Comment by robertjpayne** [comment]
@XiangNanLi can you post your constraints code, also try `mas_remakeConstraints` rather than update constraints.

**Comment by XiangNanLi** [comment]
Thanks , Sir.

`[_lblTitle mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(weakself.mas_centerX);
        make.top.equalTo(weakself.mas_top).offset(viewHeight(20));
    }];
    [_lblInitTitle mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(weakself.mas_centerX).offset(viewWidth(-85));
        make.top.equalTo(weakself.lblTitle.mas_bottom).offset(viewHeight(20));
    }];
    [_lblFinishTitle mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(weakself.mas_centerX).offset(viewWidth(85));
        make.top.equalTo(weakself.lblTitle.mas_bottom).offset(viewHeight(20));
    }];
    [_viewFlag mas_makeConstraints:^(MASConstraintMaker *make) {
        make.width.equalTo(weakself.lblInitTitle.mas_width).offset(viewWidth(-10));
        make.height.equalTo(@2);
        make.centerX.equalTo(weakself.lblInitTitle.mas_centerX);
        make.top.equalTo(weakself.lblInitTitle.mas_bottom).offset(viewHeight(8));
        make.bottom.equalTo(weakself.mas_bottom).offset(viewHeight(-8));
    }];`
when I tap the lblFinishTitle , the viewFlag 's centerX will equal to the lblFinishTitle's centerX. Also when tap the lblinitTitle ,if the viewFlag's centerX not equal to the lblInitTitle ,the viewFlag's centerX will change to equal to the lblInitTitle's centerx

**Comment by XiangNanLi** [comment]
the mas_updateConstraints is 
`
[_viewFlag mas_updateConstraints:^(MASConstraintMaker *make) {
            make.centerX.equalTo(tapView.mas_centerX);
        }];
[_viewFlag layoutIfNeeded];
`

**Comment by robertjpayne** [comment]
@XiangNanLi you'll want to use `mas_remakeConstraints` instead. You can only use `mas_updateConstraints` to update the constant value otherwise it creates additional constraints and hence why it's breaking.

**Comment by XiangNanLi** [comment]
OK , Thanks Sir.
I see.
