### ISSUE TITLE
UITableViewCell crash

### ISSUE THREAD

**Issue by haoziy1989511** [SnapKit/Masonry#338]
i customer a new subclass with UITableviewCell ,add chanage the textLabel and detailTextLabel  constraints like this 
`-(void)setModel:(*MyCustomerModel)model
{
self.textLabel.text = model.title1;
self.detailTextLabel.text = model.title2;
[self.textLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(self.textLabel.superView).offset(8);
            make.top.equalTo(self.textLabel.superView).offset(5);
        }];
[self.detailTextLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(self.textLabel.superView).offset(8);
            make.top.equalTo(self.textLabel.bottom).offset(5);
        }];
}`

when the textLabel.text is empty or nil and scrolled table;it crashed;
![image](https://cloud.githubusercontent.com/assets/12935851/15010409/729b0b9c-121e-11e6-9d57-a469e4cae7bc.png) @kouky

**Comment by robertjpayne** [comment]
@haoziy1989511 do not use constraints with the standard UILabel's on UITableViewCell. Instead create your own labels and use constraints with them.

**Comment by haoziy1989511** [comment]
@robertjpayne I resolve it by this `if (self.textLabel.text.length==0) {
            [self.contentView addSubview:self.textLabel];
        }` standard UILabel's on UITableViewCell is not a good choice,So I will new one add in cell.contentView;thx
