### ISSUE TITLE
Cycle Create  UIButton  causes the program to crash

### ISSUE THREAD

**Issue by devtofu** [SnapKit/Masonry#342]
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

![image](https://cloud.githubusercontent.com/assets/12134966/15211673/26f76134-186f-11e6-98e2-923c226fdd94.png)

this my code: 
```objective-c

// 导航栏 60个高度
    [navigationBar mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(navigationBar.superview);
        make.right.equalTo(navigationBar.superview);
        make.top.equalTo(navigationBar.superview).mas_offset(20);
        make.height.mas_offset(60);
    }];
    CGFloat padding = 15;
    __block UIButton *lastButton;
    for (NSInteger i = 0; i < 3; i++) {
        UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
        [navigationBar addSubview:button];
        
        [button mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(28);
            make.centerY.equalTo(button.superview.mas_centerY);
            if (lastButton) {
                make.right.equalTo(lastButton.mas_left).offset(-padding);
            } else {
                make.right.equalTo(button.superview.mas_right).offset(-padding);
            }
            lastButton = button;
        }];

        button.tag = i + 1000;
        [button setImage:[UIImage imageNamed:images[i]] forState:UIControlStateNormal];
        [button addTarget:self action:@selector(navigationBarItemClick:) forControlEvents:UIControlEventTouchUpInside];
        
    }


```

### help me , please.....

**Comment by robertjpayne** [comment]
@devtofu my guess is one of your `equalTo(XXX)` is being set to a nil value. Are you sure `navigationBar.superview` is not nil?

**Comment by devtofu** [comment]
@robertjpayne but UIImageView is not crash

**Comment by devtofu** [comment]
![image](https://cloud.githubusercontent.com/assets/12134966/15235983/c2b643fa-18f2-11e6-91b4-31172e25c979.png)

`navigationBar.superview` is not nil..

**Comment by devtofu** [comment]
I temporarily replaced UIButton with UIImageView, first solve the crash problem。

**Comment by robertjpayne** [comment]
@devtofu do you have the full stacktrace of the crash? I doubt it's Masonry we don't use dictionaries much.

**Comment by devtofu** [comment]
@robertjpayne  Global breakpoints do not work, look at the pictures.

![image](https://cloud.githubusercontent.com/assets/12134966/15246135/2bd0c6a4-193d-11e6-884f-2620bfcf6d3c.png)

![image](https://cloud.githubusercontent.com/assets/12134966/15246126/1eb7cac6-193d-11e6-9712-9a0cd18ca25c.png)


![image](https://cloud.githubusercontent.com/assets/12134966/15246061/d458d916-193c-11e6-9e8e-55ad687a3037.png)

**Comment by robertjpayne** [comment]
@devtofu Sorry I can't really help you with this, it doesn't look like this has anything to do with Masonry other than perhaps bad input or bad configuration of UIView's.

You mentioned it works with UIImageView rather than UIButton's which is very odd, my experience is that constraining stuff to navigation bars ( especially if they are attached to a UINavigationController ) normally just results in really buggy behavior.

You'll have to track down what part of UIButton is causing the issue but it's likely related to just a circumstantial setup you have.

**Comment by devtofu** [comment]
@robertjpayne  It doesn't matter, thank you very much, I do not think this is a Masonry problem, because we have another method of doing the same thing, it will not crash, very odd。

**Comment by devtofu** [comment]
@robertjpayne  my god....   I finally found rewrite the init method in UIButton in the category, if not import this category, will refer to it.  This is my fault. . thanks for your help again.

![image](https://cloud.githubusercontent.com/assets/12134966/15248063/b5698c72-194a-11e6-9e45-6f9ef5a83566.png)

**Comment by KhazanGu** [comment]
@devtofu How do you solve this problem? Do not use UIButton?
