### ISSUE TITLE
updateConstraints can only update constant?

### ISSUE THREAD

**Issue by tt3tt3tt** [SnapKit/Masonry#345]
updateConstraints can only update constant, can't update any one of (firstItem, secondItem, firstAttribute, secondAttribute, relation, multiplier, priority)?  one of (firstItem, secondItem, firstAttribute, secondAttribute, relation, multiplier, priority) is different as different constraint, is that right?

**Comment by robertjpayne** [comment]
@tt3tt3tt correct, `mas_updateConstraints` can *only* upgrade the constant, it also must match the same TO and FROM items/attributes:

`make.left.equalTo(otherView)` will not match `make.left.equalTo(otherView.mas_right)`, if you want to swap the TO and FROM items/attributes you need to use `mas_remakeConstraints` and rebuild the whole constraint set.
