### ISSUE TITLE
NSAutoresizingMaskLayoutConstraint iOS7 crash

### ISSUE THREAD

**Issue by bigParis** [SnapKit/Masonry#346]
I use masonry in a view, and got 
Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0xc1c75d0 UIButton:self.shareButton.width == 34>",
    "<MASLayoutConstraint:0xc1d2570 UIButton:self.moreButton.width == 34>",
    "<MASLayoutConstraint:0x3108660 UIButton:self.moreButton.right == MFChatRoomTopView:0xc29c560.right>",
    "<MASLayoutConstraint:0xc1cd930 UIButton:self.shareButton.right == UIButton:self.moreButton.left>",
    "<MASLayoutConstraint:0xc2df540 UIView:self.titleView.centerX == MFChatRoomTopView:0xc29c560.centerX>",
    "<MASLayoutConstraint:0xc2df580 UIView:self.titleView.right == UIButton:self.shareButton.left>",
    "<NSAutoresizingMaskLayoutConstraint:0xc22e1b0 MFChatRoomTopView:0xc29c560.width == 0>"
)

I set MFChatRoomTopView's frame in viewDidLayoutSubviews, it works fine in ios>=8.x but crash on ios7.Actually I don't need to set translatesAutoresizingMaskIntoConstraints = NO, but when I set this, it will not crash in NSAutoresizingMaskLayoutConstraint way.
At last, I try to add [self.view layoutIfNeeded] at the end of viewDidLayoutSubviews, and it doesn't crash any more, but, the position of subviews of MFChatRoomTopView was all wrong. How could I solve this problem? Anyone have ideas?

**Comment by bigParis** [comment]
I don't know who make the constraints before the view's init called

**Comment by robertjpayne** [comment]
@bigParis iOS by default adds some constraints when `translatesAutoresizingMaskIntoConstraints` is not turned off (it defaults to true).

If you're seeing constraint invalidations due to this turn it off and add more constraints to make up for what may or may not be missing.
