### ISSUE TITLE
remakeConstraints

### ISSUE THREAD

**Issue by ubdc** [SnapKit/Masonry#347]
In the Masonry iOS [Examples/MASExampleUpdateView.m.](https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleUpdateView.m)

`- (void)updateConstraints {

    [self.growingButton updateConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(self);
        make.width.equalTo(@(self.buttonSize.width)).priorityLow();
        make.height.equalTo(@(self.buttonSize.height)).priorityLow();
        make.width.lessThanOrEqualTo(self);
        make.height.lessThanOrEqualTo(self);
    }];
    
    //according to apple super should be called at end of method
    [super updateConstraints];
}`
when i change updateConstraints to remakeConstraints, the button's size does not change when i click the button.

**Comment by robertjpayne** [comment]
@ubdc you still need to invalidate your constraints for iOS to call `updateConstraints` you can do so by calling `[view setNeedsUpdateConstraints]`

If you want to animate constraints you will need to:

```
[view setNeedsUpdateConstraints]
[view setNeedsLayout]
[UIView animate… ^{
  [view layoutIfNeeded]
}]
```

**Comment by ubdc** [comment]
in the example [MASExampleUpdateView.m](https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleUpdateView.m), i just replace `updateConstraints` to `remakeConstraints` in `updateConstraints` method. and when i click the button, it will call:

`[view setNeedsUpdateConstraints];`
`[self updateConstraintsIfNeeded];`
`[UIView animateWithDuration:0.4 animations:^{`
`[self layoutIfNeeded];`
`}];`

but the button size does not change at all.
