### ISSUE TITLE
v1.0.1 breaks Carthage builds due to improper CocoaPods target sharing

### ISSUE THREAD

**Issue by tonyarnold** [SnapKit/Masonry#350]
<img width="792" alt="screen shot 2016-05-29 at 21 28 40" src="https://cloud.githubusercontent.com/assets/4802/15632948/54585624-25e4-11e6-8acb-5e0aab28a338.png">

These schemes should not be shared. They are causing Carthage to fail with the error: 

```
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/tonyarnold/Documents/CocoaBots Client Work/RedactedClientProject/Carthage/Checkouts/Masonry/Masonry.xcworkspace -scheme Pods-MasonryTestsLoader-Masonry -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme Pods-MasonryTestsLoader-Masonry is not currently configured for the build action.
```

**Comment by tonyarnold** [comment]
Actually, the entire workspace seems to be at fault here, not just those two schemes. I don't understand enough about what CocoaPods does to the workspace anymore, but v1.0.0 built just fine.

**Comment by robertjpayne** [comment]
@tonyarnold I'll have a look sometime this week, or if you need this in sooner feel free to submit a PR!

**Comment by robertjpayne** [comment]
Merged this up, I'm away until August though so it wont make a formal release before then (at that point probably a bunch of fixes for Xcode 8 / iOS 10 too!)

**Comment by jgafni** [comment]
@tonyarnold , I ran into the same problem.  I deleted those two schemes and it works fine.

**Comment by aaronbrethorst** [comment]
@robertjpayne sorry to bug you, but any update on this?

**Comment by robertjpayne** [comment]
Hey sorry everyone v1.0.2 has been pushed to Cocoapods, it should fix this up!
