### ISSUE TITLE
First/last baseline target min deployment rather than max deployment version

### ISSUE THREAD

**Issue by muccy** [SnapKit/Masonry#353]
Hi,
because new baseline support is defined like this:

``` obj-c
#if (__IPHONE_OS_VERSION_MIN_REQUIRED >= 80000) || (__TV_OS_VERSION_MIN_REQUIRED >= 9000) || (__MAC_OS_X_VERSION_MIN_REQUIRED >= 101100)

@property (nonatomic, strong, readonly) MASConstraint *firstBaseline;
@property (nonatomic, strong, readonly) MASConstraint *lastBaseline;

#endif
```

and CocoaPods after install sets Masonry pod target like this:
![schermata 2016-06-12 alle 12 18 28](https://cloud.githubusercontent.com/assets/18466/15990604/ca25531c-3097-11e6-9146-d36dbeb80962.png)

the macro fails and the new features are disabled.

**Comment by robertjpayne** [comment]
@muccy what version of Xcode you running?

**Comment by muccy** [comment]
Xcode 7.3.1 + CocoaPods 1.0.1

**Comment by robertjpayne** [comment]
@muccy that's because you have a minimum deployment target of iOS 6.0, we err on the extra cautious side here and disable these rather than enable them and users think they are free to use them across all iOS versions.

**Comment by robertjpayne** [comment]
In saying that, now that we're on iOS 10.0 just about it might be valid to change this.

**Comment by robertjpayne** [comment]
I'm actually going to leave this as is, if your deployment target is < 8.0 this is unsafe and you shouldn't be using it.

You can always use the `baseline` attribute.
