### ISSUE TITLE
The MASBoxValue would apparently be made better by simply wrapping its parameter in `@()`

### ISSUE THREAD

**Issue by ThePantsThief** [SnapKit/Masonry#354]
Is there a reason it doesn't do this? Seems to me that since Objective-C has support for boxing any `NSNumber` type (and most `NSValue` types) via `@(value)` syntax, Masonry should make use of that, instead of inserting a function call with a giant if-else tree…

**Comment by robertjpayne** [comment]
@ThePantsThief as far as I know @ syntax cannot box CGRect, CGSize, CGPoint or UIEdgeInsets?

**Comment by ThePantsThief** [comment]
My apologizes, I thought you could for some reason. I'll close the issue!
