### ISSUE TITLE
How to add a constant center constraint, not relative to it's super view?

### ISSUE THREAD

**Issue by CodeLife2012** [SnapKit/Masonry#355]

**Comment by robertjpayne** [comment]
@CodeLife2012 you just do `make.centerX.equalTo(50)`

**Comment by CodeLife2012** [comment]
@robertjpayne But do this will add a constraint relative super view's centerX.

Not a constant  centerX equal to 50. 

Maybe you can reopen this issue

**Comment by CodeLife2012** [comment]
My fault, seems autolayout don't allow us  to create a constant centerX and centerY constraint.

@robertjpayne

**Comment by robertjpayne** [comment]
@CodeLife2012 yea only width/height are allowed as installed on self
