### ISSUE TITLE
iOS 10 compability

### ISSUE THREAD

**Issue by joaopdcgarcia** [SnapKit/Masonry#364]
I'm currently working on an app that uses Masonry to layout constraints in code. 
I've noticed on my device (iOS 10) that some of the constraints stopped working. 
Has anyone else encountered issues on iOS 10?

**Comment by nevinjethmalani** [comment]
Yes I have seen the same issue but not using this pod. I have noticed it just when testing in iOS 10

**Comment by robertjpayne** [comment]
@joaopdcgarcia @nevinjethmalani probably the iOS 10 layout engine is more strict and you have constraint combinations that are now failing, are you getting any debug logs from the device you can share or is it silent failures when running in debug mode?

**Comment by nevinjethmalani** [comment]
I am running a live version of our app on an iOS 10 device and therefore do not have access to the debug logs. They are very basic constraints. We are using them to create a parallax effect.

**Comment by robertjpayne** [comment]
@nevinjethmalani it's impossible to say really, the tests all pass in Xcode 8, your best bet is to load it up in Xcode 8 and debug it and see if there is any issues.

If there are, please feel free to open up new issues with specific Masonry bits that are broken in iOS 10.0

**Comment by stevenkitter** [comment]
all layout is down in iOS 10 ,i am using 0.22
