### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by iTofu** [SnapKit/Masonry#365]
I want using animation with Masonry, but there are some questions...

See this image:

<img width="388" alt="2016071501" src="https://cloud.githubusercontent.com/assets/10044430/16878123/ec367cf0-4add-11e6-969b-2c412c3f40f8.png">

This is my bottom view:

````objc
UIView *bottomView = [[UIView alloc] init];
[self addSubview:bottomView];
[bottomView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.right.equalTo(self);
    
    CGFloat height = 100.0f;

    make.height.equalTo(@(height));
    make.bottom.equalTo(self).offset(height);
}];
````

Animation code:

````objc
[UIView animateWithDuration:self.animationDuration delay:0 options:UIViewAnimationOptionCurveEaseOut animations:^{
    
    [self.darkView setAlpha:self.darkOpacity];
    [self.darkView setUserInteractionEnabled:YES];
    
    [self.bottomView mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.left.right.equalTo(self);
        
        CGFloat height = 100;
        make.height.equalTo(@(height));
        make.bottom.equalTo(self);
    }];
    [self layoutIfNeeded];
    
} completion:nil];
````

But animation is:

![2016071502](https://cloud.githubusercontent.com/assets/10044430/16878281/85eb6e96-4ade-11e6-8e6e-5b19957f8406.gif)

Did I do something wrong?

**Comment by Nicejinux** [comment]
I think you have to mas_updateConstraints.

Why don't you try this.

    [self.bottomView mas_updateConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self);
    }];

**Comment by iTofu** [comment]
I found a solution... WTF...

Before animation,

````objc
[self layoutIfNeeded];

// [UIView animateWithDuration:...]
````

It works... Why?

**Comment by iTofu** [comment]
@nickcheng 
Thank you! Could you tell me what's the difference between `mas_updateConstraints` and `mas_remakeConstraints`?

**Comment by Nicejinux** [comment]
"remake" means remove all constraints and make again.
"update" means just update what you've defined.

so if you want to modify constraints what you've defined, use update_constraints
but if you want to add new constraints, you have to use remake_constraints.

**Comment by iTofu** [comment]
So `remake` will clear all old constraints? And `update` just update constraint what I reset?

**Comment by Nicejinux** [comment]
yes. that's what I know.

**Comment by iTofu** [comment]
Well, Thank you!

**Comment by iTofu** [comment]
And this question because view's constraints has not been created before animation, so we should call `[self layoutIfNeeded];` before animation.

**Comment by iStarEternal** [comment]
- (void)showSheet {
    UIView *sheet = ...
    [self.view addSubview:sheet];
    [sheet mas_makeConstraints:^(make){
         make.left.right.equalTo(@0);
         make.height.equalTo(@120);
         make.bottom.equalTo(@120);
    }]
    dispatch_delay(0.01, ^{
       [sheet layoutIfNeeded];  
       [UIView animateWithDuration:0.25 animations:^{
            [sheet mas_updateConstraints:^(MASConstraintMaker *make) {
                 make.bottom.equalTo(@(0))
             }];
            [sheetlayoutIfNeeded];
         }];
    });
}
Code is there , That's writen in Win7 text editor,
