### ISSUE TITLE
What is the appropriate way to make constraints in initializer methods?

### ISSUE THREAD

**Issue by yangcaimu** [SnapKit/Masonry#369]
Apple recommend "Do not Use Accessor Methods in Initializer Methods and dealloc" with this document: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmPractical.html

If I want to make constraints in the initializer methods, how I write better code?
```Objective-C
@interface CustomView : UIView
@property (nonatomic, strong) UIView *viewLeft;
@property (nonatomic, strong) UIView *viewRight;
@end

@implementation CustomView

- (instancetype)init {
    self = [super init];
    if (self) {
        UIView *viewLeft = [UIView new];
        _viewLeft = viewLeft;
        [self addSubview:_viewLeft];
        [_viewLeft mas_makeConstraints:^(MASConstraintMaker *make){
            make.left.top.bottom.mas_equalTo(self);
        }];
        
        UIView *viewRight = [UIView new];
        _viewRight = viewRight;
        [self addSubview:_viewRight];
        [_viewRight mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.top.bottom.mas_equalTo(self);
            // by accessor set up
            make.left.mas_equalTo(self.viewLeft.mas_right);
            // or by iVar set up
            make.left.mas_equalTo(self -> _viewLeft.mas_right);
        }];
    }
    return self;
}

@end
```

**Comment by robertjpayne** [comment]
@yangcaimu Apple recommends it because it can commonly crop up bugs, however, to be honest I do this in init all the time and I've never had issues.

The issues arise when an accessor does some initialisation but because you're in an init method you're probably in an undefined state.

**Comment by yangcaimu** [comment]
Yes, I wrote a [demo](https://github.com/yangcaimu/UseAccessorMethodsInInitializerMethodsAndDeallocDemo) presentation issue.
