### ISSUE TITLE
Add inset property

### ISSUE THREAD

**Issue by iwill** [SnapKit/Masonry#372]
We CAN set offset to left and top in a single line:
```objc
make.left.top.equalTo(superview).offset(padding);
```

But, we MUST set offset to left and right:
```objc
make.left.equalTo(superview).offset(padding);
make.right.equalTo(superview).offset(- padding);
```
OR:
```objc
make.left.right.equalTo(superview).insets(UIEdgeInsetsMake(0.0, padding, 0.0, padding));
```

But I LIKE this:
```objc
make.left.right.equalTo(superview).inset(padding);
```

**Comment by robertjpayne** [comment]
@iwill would be happy to merge a PR for this but at this point we're not spending any time ourselves on feature dev!

**Comment by iwill** [comment]
@robertjpayne Done!

**Comment by iwill** [comment]
@robertjpayne When will you release this feature?
