### ISSUE TITLE
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `Masonry iOS Examples`..

### ISSUE THREAD

**Issue by DozEuto** [SnapKit/Masonry#373]
pod install
There has a error

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `Masonry iOS Examples`..

 #  from /Users/xuchenliang/Documents/git project/Masonry/Podfile:6
 #  -------------------------------------------
 #  
 >  target 'Masonry iOS Examples', :exclusive => true do
 #    xcodeproj 'Examples/Masonry iOS Examples'
 #  -------------------------------------------

**Comment by robertjpayne** [comment]
@DozEuto should be fixed up now
