### ISSUE TITLE
Using topLayoutGuide in a UIView without reference to UIViewController

### ISSUE THREAD

**Issue by andybee** [SnapKit/Masonry#375]
I am attempting to write a UIView that can be re-used in different view controllers with or without a topLayoutGuide (it may be presented "full screen", as part of another view, or with the usual iOS status bar across it and so the background of the view should wrap underneath).

Typically, to keep the view logic self-contained I implement the `updateConstaints` method on the UIView and add the Masonry calls there.

However, Apple expose the topLayoutGuide on the UIViewController, which means the only way to keep the logic self-contained is to expose the VC to the View in a weak property on the view. Whilst this works, it feels a bit... erk.

I've tried putting all the subviews that may need to nudge down inside a contentView and exposing that as a property of the UIView so the view controller could attach a constraint to that just for nudging it down when required, but I quickly enter conflicts this way because the standalone view needs to set the edges of the content view to match itself, then the VC tries to bring the top down.

Am I missing something that might make this cleaner/simpler?

**Comment by robertjpayne** [comment]
@andybee there's nothing we can really do for you here, you may just expose the layout guide rather than the whole VC?
