### ISSUE TITLE
Update Travis Image to Xcode 8.0

### ISSUE THREAD

**Issue by fabb** [SnapKit/Masonry#386]
This repo still uses on a Travis Xcode 7.3 image: https://github.com/SnapKit/Masonry/blob/master/.travis.yml#L3

Should be updated (+ fixed if necessary) for Xcode 8.

**Comment by robertjpayne** [comment]
Integrated thanks to your PR 👍

**Comment by fabb** [comment]
Sure, you're welcome! Thanks for merging.
