### ISSUE TITLE
animation isn't work in iOS 10

### ISSUE THREAD

**Issue by codesourse** [SnapKit/Masonry#391]
[_indicatorView updateConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(sender.tag*BARWID);
    }];
    
    [UIView animateWithDuration:3
                     animations:^{
                         [_indicatorView layoutIfNeeded];
                     }];

**Comment by HoneyLuka** [comment]
I think you can test it in a demo project. Make sure it is a bug.

**Comment by Zammy** [comment]
I am having similar trouble. I do it exactly like in the example but I am not getting any animation.
I tested the demo project and it works there so I am not sure how to help you out.

**Comment by Zammy** [comment]
Just tested with iOS 9.3 simulator and there are no problems with animations.

**Comment by Zammy** [comment]
Ok, we found out the problem. You need to call layoutIfNeed on the superview!

**Comment by robertjpayne** [comment]
@Zammy was always the case, sometimes between iOS versions the superview of known UIKit views changes though so things break!

**Comment by robertjpayne** [comment]
Closing as I believe this is resolved, re-open if you need to
