### ISSUE TITLE
hello, autolayout crash on iOS 10

### ISSUE THREAD

**Issue by hackjie** [SnapKit/Masonry#407]
masonsy :pod 'Masonry', '1.0.2'
iOS 10.2

when i run code like these:

![2016-12-20 9 59 53](https://cloud.githubusercontent.com/assets/9956115/21335623/173ba946-c69b-11e6-82c8-c0bccd5385cf.png)

it will stop at this position:

![2016-12-20 9 59 44](https://cloud.githubusercontent.com/assets/9956115/21335625/1a4356de-c69b-11e6-83e6-c26a22118f9a.png)

hope your answer quickly. thanks!

**Comment by knighterrantsky** [comment]
have you resolved?  i have the same problem

**Comment by hackjie** [comment]
no, i changed the view inside
