### ISSUE TITLE
Swift Masonry

### ISSUE THREAD

**Issue by chenxuhunoc** [SnapKit/Masonry#412]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 Masonry Version         | e.g. 1.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

Do you have Swift version Masonry ?

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
@chenxuhunoc see `SnapKit/SnapKit` on GitHub 👍

**Comment by chenxuhunoc** [comment]
Do you have Swift version Masonry ?
