### ISSUE TITLE
THX a lot.

### ISSUE THREAD

**Issue by macong0420** [SnapKit/Masonry#419]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 Masonry Version         | e.g. 1.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
Thanks! 👍
