### ISSUE TITLE
A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant

### ISSUE THREAD

**Issue by app111** [SnapKit/Masonry#427]
### New Issue Checklist
//source
            [self.tabBarController.view addSubview:self.pageAdView];
            [self.pageAdView mas_makeConstraints:^(MASConstraintMaker *make) {
                    make.edges.equalTo(self.tabBarController.view);
            }];
..............................................
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <PageAdView: 0x10198c2b0; frame = (0 0; 0 0); clipsToBounds = YES; layer = <CALayer: 0x174425120>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.'

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 10.2.1
 Masonry Version         | e.g. 1.0.1
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by martres** [comment]
Hi,

Do you find a solution ? I got the same error ... 

Thank

**Comment by amita214** [comment]
I have the same issue does anyone have a solution?
I think I will set each side separately to resolve my crash.

**Comment by zhenyiyi** [comment]
I have a same issue. 

Masonry Version	e.g. 1.0.2

`[self.sidebarVC.view mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.navigationController.view);
    }];`

NSLayoutConstraint for <UIView: 0x101ec04c0; frame = (0 0; 375 667); hidden = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x17064fba0>; layer = <CALayer: 0x1702303e0>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.

**Comment by zhenyiyi** [comment]
I guess the subviews layouts incorrect
.

**Comment by lhp3851** [comment]
I met the same issue when use SnapKit 4.0 in a swift 4.0 Project ,
Xcode version :9.0, 
iOS 11

**Comment by antonijap** [comment]
Same here.

**Comment by JianboYan** [comment]
same issue here. any solution?

**Comment by zhouyu0616** [comment]
#185 I think can refer to ashare80's answer in this question。

**Comment by sakubek** [comment]
Maybe you forgot to addsubview your label or something

**Comment by barylevy** [comment]
check if parent view is nil
self.pageAdView in the Q

**Comment by app111** [comment]
it's right

**Comment by app111** [comment]
it's right
