### ISSUE TITLE
Is function `equalTo` Kind of Decorator pattern, can someone explain it for me ? Thank you.

### ISSUE THREAD

**Issue by Jonwei** [SnapKit/Masonry#446]
In file `MASConstraint.m`, function `-equalTo` as below,  how to understand it ? I mean, it doesn't receive param, but in use,  it do receive a param like ` equalTo(self.view.mas_width)` 

```
...

- (MASConstraint * (^)(id))equalTo {
    return ^id(id attribute) {
        return self.equalToWithRelation(attribute, NSLayoutRelationEqual);
    };
}

...
```

**Comment by Jefrl** [comment]
* As you said, this is not the parameter passing, but get a **block** by equal method, and then execute the **block**  with the parameters ;

* If you ask like this, it means you need to learn the Block syntax, and it's relatively hard  in the Block syntax sugar, with the parameters and return value, and the return value is a Block that is used to complete the chain programming feature

* This is a Block with  parameters and return value, and the return value is always a class object that contains the Block attribute, and it's a bit hard if it's just contact

```
/**
 *	Sets the constraint relation to NSLayoutRelationEqual
 *  returns a block which accepts one of the following:
 *    MASViewAttribute, UIView, NSValue, NSArray
 *  see readme for more details.
 */
- (MASConstraint * (^)(id attr))equalTo;

// @implementation ...
- (MASConstraint * (^)(id))equalTo {
    return ^id(id attribute) {
        return self.equalToWithRelation(attribute, NSLayoutRelationEqual);
    };
}

- (MASConstraint * (^)(id, NSLayoutRelation))equalToWithRelation {
    return ^id(id attribute, NSLayoutRelation relation) {
        if ([attribute isKindOfClass:NSArray.class]) {
         ...
            return compositeConstraint;
        } else {
           ...
            return self;
        }
    };
}
...

```

**Comment by Jonwei** [comment]
@Jefry thanks for your reply.
