### ISSUE TITLE
Are Masonry ready to support iPhone X？

### ISSUE THREAD

**Issue by emptywalker** [SnapKit/Masonry#455]

**Comment by cntrump** [comment]
just need add safeAreaLayoutGuide support.
https://github.com/SnapKit/Masonry/pull/456

**Comment by crazytom26** [comment]
Not find the" mas_safeAreaLayoutGuideTop"  MASViewAttribute in the recently download version

**Comment by robertjpayne** [comment]
Released to Cocoapods just now via v1.1.0
