### ISSUE TITLE
unrecognized selector sent to instance 0x7fcd2ee097e0 

### ISSUE THREAD

**Issue by oddisland** [SnapKit/Masonry#458]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ x ] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ x ] I have filled out this issue template.

### Issue Info

 Info  unrecognized selector sent to instance 0x7fcd2ee097e0               | Value                               |
-------------------------|-------------------------------------|
 Platform   ios             | e.g. ios/osx/tvos
 Platform Version   9.0     | e.g. 8.0
 Masonry Version    1.0.2    | e.g. 1.0
 Integration Method  cocoapods    | e.g. carthage/cocoapods/manually
 

### Issue Description

-[UIView mas_makeConstraints:]: unrecognized selector sent to instance 0x7fcd2ee097e0
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_makeConstraints:]: unrecognized selector sent to instance 0x7fcd2ee097e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010297a1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001022dcf41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001029fa914 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKit                               0x000000010301d0bd -[UIResponder doesNotRecognizeSelector:] + 295
	4   CoreFoundation                      0x00000001028fd178 ___forwarding___ + 1432
	5   CoreFoundation                      0x00000001028fcb58 _CF_forwarding_prep_0 + 120
	6   demo5                               0x00000001019cc44b -[ViewController viewDidLoad] + 267
	7   UIKit                               0x0000000102f92d51 -[UIViewController loadViewIfRequired] + 1235
	8   UIKit                               0x0000000102f9319e -[UIViewController view] + 27
	9   UIKit                               0x0000000102e66d17 -[UIWindow addRootViewControllerViewIfPossible] + 122
	10  UIKit                               0x0000000102e6741f -[UIWindow _setHidden:forced:] + 294
	11  UIKit                               0x0000000102e7a2bf -[UIWindow makeKeyAndVisible] + 42
	12  UIKit                               0x0000000102dee015 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4711
	13  UIKit                               0x0000000102df3245 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1720
	14  UIKit                               0x00000001031aec6c __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 924
	15  UIKit                               0x000000010357c3ef +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	16  UIKit                               0x00000001031ae865 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 249
	17  UIKit                               0x00000001031af0c3 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 668
	18  UIKit                               0x0000000103b0cc11 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 262
	19  UIKit                               0x0000000103b0caca -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 444
	20  UIKit                               0x00000001037fab9c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 420
	21  UIKit                               0x00000001039f5c3e _performActionsWithDelayForTransitionContext + 100
	22  UIKit                               0x00000001037fa998 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 231
	23  UIKit                               0x000000010357ba4c -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	24  UIKit                               0x0000000102df1ac6 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 523
	25  UIKit                               0x00000001033ba523 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 369
	26  FrontBoardServices                  0x0000000106fd6158 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 338
	27  FrontBoardServices                  0x0000000106fdec4d __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 235
	28  libdispatch.dylib                   0x000000010624f43c _dispatch_client_callout + 8
	29  libdispatch.dylib                   0x0000000106254af4 _dispatch_block_invoke_direct + 592
	30  FrontBoardServices                  0x000000010700a672 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	31  FrontBoardServices                  0x000000010700a328 -[FBSSerialQueue _performNext] + 464
	32  FrontBoardServices                  0x000000010700a897 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	33  CoreFoundation                      0x000000010291d2b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	34  CoreFoundation                      0x00000001029bcd31 __CFRunLoopDoSource0 + 81
	35  CoreFoundation                      0x0000000102901c19 __CFRunLoopDoSources0 + 185
	36  CoreFoundation                      0x00000001029011ff __CFRunLoopRun + 1279
	37  CoreFoundation                      0x0000000102900a89 CFRunLoopRunSpecific + 409
	38  GraphicsServices                    0x00000001073f09c6 GSEventRunModal + 62
	39  UIKit                               0x0000000102df4d30 UIApplicationMain + 159
	40  demo5                               0x00000001019cd73f main + 111
	41  libdyld.dylib                       0x00000001062cbd81 start + 1
	42  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

how to fix this error?

**Comment by splitgrace** [comment]
Have the same error.

**Comment by oddisland** [comment]
- Just add all resource under Masonry folder into Build Phases -> Compile Sources .
- It will be work!
