### ISSUE TITLE
Version 1.1.0 not listed in changelog / docs

### ISSUE THREAD

**Issue by alphastryk** [SnapKit/Masonry#471]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | N/A
 Masonry Version         | 1.1.0
 Integration Method      | cocoapods
 

### Issue Description

The changelog [https://github.com/SnapKit/Masonry/blob/master/CHANGELOG.md] does not list version 1.1.0, but it shows up via cocoapods. What was changed with this version? Is that documented somewhere?

**Comment by bplattenburg** [comment]
This appears to be resolved now - https://github.com/SnapKit/Masonry/releases/tag/v1.1.0
